111 impl table components
academic-relations/ar-002-clubs pull request #112
Opened 2024-05-03 14:32 UTC by wjeongchoi

# 요약 \*

It closes #111 

# 스크린샷

<img width="936" alt="스크린샷 2024-05-03 오후 11 32 01" src="https://github.com/academic-relations/ar-002-clubs/assets/144689054/8c939cf6-99e2-401d-95d0-cd4c6605bcb1">

# 이후 Task \*

- 페이지별 Table 구현

2024-05-04 04:51 UTC, predict-woo approved these changes
화살표 아이콘이 너무 아래로 내려가있는 듯 합니다.
+ 화살표 아이콘이 있을때, text 중심으로 center가 되어야 합니다. 현재 text + icon 중심으로 center가 되어있습니다.
이부분 제외하고 LGTM!

2024-05-04 17:16 UTC, babycroc requested changes
호 리뷰를 하다보니 뭔가 너무 많이 고쳐달라고 요구하는 결론이 난 것 같긴 한데.. ㅇ.ㅇ
내가 생각했을 때는...??? TableCell이 prop을 많이 받는 것보다는 크기나 패딩 같은 기본 레이아웃만 잡아주고 내부 내용은 children으로 받아서 보여주는 게 더 깔끔할 것 같아서 제안해봤습니다 질문도 언제든 환영
(내가 만약 나중에 이상한 cell 종류를 또 추가하면 여기서 계속 덕지덕지 타입만 붙어나갈 것 같기두 하구..)

2024-05-04 17:16 UTC, babycroc commented on packages/web/src/common/components/Table/TableCell.tsx
> +  text,
흐으으으음 사실 고민되는 부분이 사람들이 `TableCell`을 기존의 html tag인 `td`마냥 
`<TableCell>{...}</TableCell>` 이렇게 썼으면 좋겠는데...
그래서 text 같은 것두 prop으로 받기보다는 그냥 `<TableCell>text</TableCell>` 이렇게 써도 되게끔...????

그러면 사실 요 아이에서 Button / Buttons 타입을 가지고 있기 보다는 `TableCellWithButtons` 같은 걸 만들어서 사용하는 게 나을 것 같군.. 혹시 이해했으려나 약간 요런 느낌의 컴포넌트가 되겟지 (이러면 button 개수도 조절 가능(???))
```
const TableCellWithButtons: React.FC<Props> = ({
  text = [""],
  onClick = [() => {}],
}) => (
  <TableCell width={width}>
    <ButtonsWrapper>
      <TextButton text={text[0]} onClick={onClick[0]} />
      <CellText isGray>/</CellText>
      <TextButton text={text[1]} onClick={onClick[1]} />
      <CellText isGray>/</CellText>
      ...
    </ButtonsWrapper>
  </TableCell>
);
```

2024-05-04 17:16 UTC, babycroc commented on packages/web/src/common/components/Table/TableCell.tsx
> +    {type === "Tag" && <CellTagInner color={color}>{text}</CellTagInner>}
사아실 위에서 말한대로 `TableCell`을 고치면 사람들이 이런 방법으로 잘 써줄 것 같긴 함
```
<TableCell><Tag {...} /></TableCell>
```

2024-05-04 17:16 UTC, babycroc commented on packages/web/src/common/components/Table/TableCell.tsx
> +  text,
내가 피그마에서 `TableCell`을 만들고 타입을 여러개로 나눠서 사용하고 있는 이유는 사실 피그마에서 편하게 쓰기 위함이어서.. 꼭 그 타입 구분 / 컴포넌트 구조를 따르지 않아도 돼요..!!! (안 따르는 것이 더 좋을수도..)

2024-05-04 17:16 UTC, babycroc commented on packages/web/src/common/components/Table/TableCell.tsx
> +);
사아실 위에서 말한대로 `TableCell`을 고치면 이것도 필요없겟당..

2024-05-04 17:16 UTC, babycroc commented on packages/web/src/common/components/Table/TableCell.tsx
> +`;
눈치 못 챘을 것 같지만 ㅎㅎ cell의 width보다 길어지는 text가 들어오면 한 줄 + ...로 보여지게 해놔서 이것도 이 PR에서 처리해줘!! 

<img width="780" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/33417582/9a3aec37-319d-4980-9469-7bcf4ff6b985">
<img width="703" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/33417582/f82df4c7-0256-4163-b582-3b65aea8cab6">

2024-05-04 17:22 UTC, wjeongchoi commented on packages/web/src/common/components/Table/TableCell.tsx
> +    {type === "Tag" && <CellTagInner color={color}>{text}</CellTagInner>}
아 이거 빨간색 태그가 없어서 가져다쓰는데 실패했어

2024-05-04 17:35 UTC, babycroc commented on packages/web/src/common/components/Table/TableCell.tsx
> +    {type === "Tag" && <CellTagInner color={color}>{text}</CellTagInner>}
는 어케 하기로 했는지 context 공유를 위해 슬랙 DM을 캡쳐해서 첨부합니다
<img width="625" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/33417582/e9206d4a-069e-4450-8c59-c4a840790657">

2024-05-04 18:42 UTC, wjeongchoi commented on packages/web/src/common/components/Table/TableCell.tsx
> +);
default나 header 같은 type까지 없애면 오히려 table 만들 때 더 번거로워질 것 같아서 type 일부는 그대로 두고 대신 children 받을 수 있게 수정했어요! switch로도 수정했습니당

2024-05-05 09:37 UTC, babycroc approved these changes
코멘트 하나 남긴 거만 반영해줭 완전 조아요~~~ 빠른 반영 감사합니다

2024-05-05 09:37 UTC, babycroc commented on packages/web/src/common/components/Table/TableButtonCell.tsx
> +      ))}
key 추가 필요

2024-05-05 11:18 UTC, merged