1130 meeting announcement remaining backend issue list
academic-relations/ar-002-clubs pull request #1160
Opened 2024-10-09 11:52 UTC by oRE-o

# 요약 \*

It closes #1130 

현재 새로 작업이 된 Meeting 관련 Schema하고 이미 개발되어 있는 meeting controller / drizzle schema 사이에 차이가 꽤나 있었습니다
MEE001 - 004에 지원하는 기능들에 각각이 정상 작동하도록 리팩토링 / schema에 coulmn 추가 / 변경을 진행했습니다.
혹시 다른 문제가 발생하는 지 알려주시면 추가적으로 작업하겠습니다,
우선 가능한대로 API는 최신화를 시켜두어서 기능 작동 여부를 테스트해주시고 피드백 해주시면 감사하겠습니다..!

# 스크린샷

# 이후 Task \*

- 없음

2024-10-12 04:30 UTC, Engineer-JJHaMa requested changes
👍 잘 작동하는거 같아요! 코멘트 확인하여 구조만 고치고 머지합시다!

2024-10-12 04:30 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.controller.ts
❗ meeting 하단에 announcement 모듈을 만들어서 전부 옮기야 합니다!

2024-10-12 04:30 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.service.ts
👍 👍 로직 자체는 큰 문제가 없어 보입니다!

2024-10-12 04:30 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.controller.ts
❗ meeting 모듈 하위에 anouncement 모듈을 만들어서 전부 옮겨야 할거 같아요!

2024-10-12 04:30 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.controller.ts
💬 MEE-001의 입력 중 tag 는 클라이언트가 입력하는 것이 아닌  분과회의를 그룹핑하기 위한 요소입니다. 입력에서 없애는게 좋아 보여요!

2024-10-30 18:57 UTC, oRE-o commented
말씀해주신 이슈를 모두 해결했습니다.
수정 사항은 다음과 같습니다 :
- meeting schema의 refactoring을 완료
- MEE001에서 tag를 더 이상 Client로부터 입력값으로 받지 않도록 수정
- meeting 하위, meeting/announcement 모듈을 생성
- meeting/announcement 모듈 내의 controller에 MEE001 ~ 004까지의 Meeting announcement 관련 API를 이동 **(meeting -> meeting/announcement)**
- MEE001~004의 역할과 관련한 service도 모두 announce.service 내로 이동을 완료

+  repository는 그대로 meeting 것을 사용합니다. 혹시 이것도 옮겨야 하면 말씀해주세요! ☺️

2024-10-31 08:16 UTC, merged