Impl MEE 006 008 010 api
academic-relations/ar-002-clubs pull request #1217
Opened 2024-11-19 12:05 UTC by ChaeyeonAhn

# 요약 \*

It closes #1215

- [ ] MEE006 구현
- [ ] MEE008 구현
- [ ] MEE010 구현
- [ ] 테스트

# 스크린샷

# 이후 Task \*

- 없음

2024-11-20 15:52 UTC, Engineer-JJHaMa requested changes
👍 궁금한 사항들 남겨두었고, 안건 모듈을 만들어서 다시 확인해보면 좋을 것 같아요!

2024-11-20 15:52 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.service.ts
> +      throw new HttpException("Executive not found", HttpStatus.NOT_FOUND);
💊  Executive가 아닌 경우는 unauthorized가 나을거 같아요

2024-11-20 15:52 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.repository.ts
> +        const getMax = await tx
❓ 혹시 mapping 테이블에 agenda가 처음 들어가는 경우에 getMax가 비어있을 경우에 잘 처리가 되나요?

2024-11-20 15:52 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.repository.ts
> +        const getMax = await tx
?. 연산을 이용하면 자동으로 0으로 넣어주나..?

2024-11-20 15:52 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.repository.ts
> +      .update(MeetingAgenda)
❓ Update 시에 deletedAt을 검사하지 않아도 되나요? 나아가서, AgendatId가 유효한지(테이블에 존재하는 아젠다가 맞는지, 의도한 미팅에 대한 아젠다가 맞는지) 검사할 필요는 없나요?

2024-11-20 15:52 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.service.ts
> +    await this.meetingRepository.deleteMeetingAgendaMapping(
❓ agenda 삭제시에 mapping만 hard delete하는 것으로 보이는데, 상관없나요?

2024-11-24 18:06 UTC, ChaeyeonAhn commented
Update 11/25 

1. meeting schema 변경: 
 - Meeting 테이블에 statusEnum 추가했습니다. (공고 게시 = 1 (디폴트), 안건 공개 = 2, 회의 종료 = 3) db에도 반영했어요. 
 - Meeting Mapping 테이블에 createdAt, updatedAt, deletedAt 추가
2. agenda 폴더 새로 생성해서 MEE 6, 8, 10은 그리로 옮겼습니다.
3. 하마 오빠 코멘트 반영 repository 코드 수정!
4. 테스트 완료 
 - Meeting과 Agenda의 매핑 생성 (Meeting의 statusEnum이 1에서 2 되는지 확인 완료)
 - MeetingMapping row 지우면 
   - MeetingMapping의 row에서 deletedAt 업데이트 되는지 확인 완료
   - 그 Meeting과의 모든 매핑이 지워졌을 경우 Meeting에서 statusEnum이 2에서 1 되는지 확인 완료)
 - 그 외 기본적인 post, patch, delete 확인 완료
 - (놓친 게 있을 지도 모르긴 합니다만..! 최대만 여러번 돌려봤어요.)

주요 변경 사항은 // CHACHA: 이런 식으로 써 놓아서, 거기 위주로 봐 주시면 됩니다.
최종 머지하기 전엔 코멘트 지울게요! 🚀  

@Engineer-JJHaMa

2024-11-24 22:57 UTC, Engineer-JJHaMa approved these changes
👍 👍 주석도 너무 잘 달아줘서 고맙고 지울 필요는 없어요! 본인이 고민했다는 것은 분명 나중에 이 코드를 보는분들도 고민할 것 같으니까요! 코멘트 확인하고 머지해주세요:)

2024-11-24 22:57 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.repository.ts
> +          .where(and(eq(MeetingMapping.meetingId, meetingId)));
💊 아마 하나의 미팅에 포함된 아젠다 개수가 그렇게 많지는 않을거라(많아야 20개 정도?) 크게 문제는 되지 않지만, soft delete 된 row 개수가 궁금한 거라면 count 이용하면 응답을 더 깔끔하게 받을 수 있을것 같아요!

2024-11-24 22:57 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/agenda/agenda.service.ts
❓  원래는 서비스 + 컨트롤러 + 레포지토리가 전부 모듈 안으로 들어오는게 좋다고 생각했는데, 이번에는 한 쿼리가 agenda가 아닌 테이블도 건드리다 보니까 그 범위가 애매하다고 느껴집니다. 가능한 한 agendarepository 안으로 가져오고, 한 트랜잭션으로 묶이지 않아도 괜찮을 것 같은 쿼리를 분리하는 것에 대해 어떻게 생각해요?

2024-11-26 13:06 UTC, merged