1219 use react hook form for activity report
academic-relations/ar-002-clubs pull request #1228
Opened 2024-11-25 18:20 UTC by Davidace136

# 요약 \*
It closes #1219 

# 스크린샷
<img width="1440" alt="스크린샷 2024-11-26 오전 2 59 03" src="https://github.com/user-attachments/assets/1c91c94b-a3f8-4836-a641-33867cbcd651">
<img width="1440" alt="스크린샷 2024-11-26 오전 2 59 19" src="https://github.com/user-attachments/assets/a3aa1d2b-b121-44e6-99cc-6933b66fd75b">
<img width="1440" alt="스크린샷 2024-11-26 오전 2 59 10" src="https://github.com/user-attachments/assets/f9770e68-205d-47b6-a216-4a9e2acdbf76">
<img width="1440" alt="스크린샷 2024-11-26 오전 2 59 14" src="https://github.com/user-attachments/assets/55da5147-fad6-418e-aff9-9f2365b97c3c">

+ PastActivityReportModal에서 ActivityReportForm 사용 예시 보는 방법:
아래 사진처럼 117(Sparcs Test 동아리)로 임의값 수정한 뒤 register club 페이지로 가서 동아리 신청 클릭 후 Sparcs Test 선택하면 하단에 활동보고서 관련 섹션이 만들어짐
<img width="1150" alt="스크린샷 2024-11-26 오전 2 58 48" src="https://github.com/user-attachments/assets/f1d705c6-ce1e-4b12-b417-d894ae7237ce">

# 이후 Task \*

- 현재 PR은 "edit" activity report에 한해서만 migration을 진행했기 때문에 "create" activity report에 대해서도 비슷한 작업이 필요. 추후 다른 issue 만들어서 진행 예정

2024-11-29 08:29 UTC, babycroc approved these changes
코멘트 단거 (특히 003 008 관련된거!!!!) 고쳐서 머지하고 후속 잡업 진행해주세용~~

+실행해봤는데 메인 제목이랑 form 사이 gap이 사라져서 요거 추가해주고
<img width="1323" alt="image" src="https://github.com/user-attachments/assets/04141ee3-852c-4bc2-bb76-b5bd2b75d7e5">

보니까 인원 선택 표도 화면 너비가 좁으면 삐져나가네요 요것두 챙겨주세용

2024-11-29 08:29 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
> +  const formCtx = useForm<ApiAct003RequestBody>({ mode: "all" });
여기 보면 타입 003인데

2024-11-29 08:29 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
> +  const { mutate } = usePutActivityReportForNewClub();
이 api는 008인데용? 뭔가 미스매치가 있는 것 같은데 확인 부탁드립니닥

2024-11-29 08:29 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
> +  const { mutate } = usePutActivityReportForNewClub();
둘이 완전 동일한 타입일 수는 있는데, 그래도 api 분리해서 사용해주세요 `usePutActivityReportForNewClub`랑 완전히 똑같은 `usePutActivityReportForClub` 만들던지 해서
008은 왠지 신규 등록 활보 작성 떄문에 추가된 애였던거같음 (확실하진 않음)

2024-11-29 08:29 UTC, babycroc commented on packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
> +            </FlexWrapper>
아 요기 때메 `asModal` prop이 들어간거군.... 뭔가 애매하긴 한데 
변수명을 `canCancel`이나 `isCancellable`이나 뭐 그런걸로 바꾸는 게 좀 더 직관적일거같음
사실상 여기서 모달이냐 아니냐의 차이는 그거 뿐이니까..

2024-12-01 15:59 UTC, jooyeongmee commented
의도한건지 모르겠는데 활동 보고서 수정 페이지 전체적으로 피그마랑 ui가 다른 것 같습니다.
1. 제목 "활동 보고서 작성" 에서 "활동 보고서 수정"으로 수정
2. 활동 정보, 활동 인원, 활동 증빙 Section이 없고 Card 모양도 없는 것 같아요

2024-12-01 16:29 UTC, jooyeongmee requested changes

2024-12-01 16:29 UTC, jooyeongmee commented on packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
useGetParticipants 에 mock 연결 안 해줘서 목으로 실행하면 해당 부분 에러 납니다
시간 되시면 mock 추가하거나 todo로 남겨주세요

2024-12-01 16:29 UTC, jooyeongmee commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
> +      // formCtx.reset(_.omit(activityReportData, "clubId"));
이 부분 현재 form data(ApiAct003RequestBody) 에는 clubId가 없고 reset 하려는 데이터가 ApiAct003RequestBody 타입 속성들과 동일하므로 그냥 reset(data) 해도 될 것 같습니다

2024-12-01 16:29 UTC, jooyeongmee commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
> +    formCtx.handleSubmit(_data => submitHandler(_data, e))();
혹시 이거 그냥 form data를 받기 위해서 따로 정의한거면 위에 submitHandler에서 파라미터로 data 받을 필요 없이 바로 formCtx의 getValues 사용하는건 어떨가요?

2024-12-01 16:29 UTC, jooyeongmee commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
> +        <ActivityReportForm
혹시 기존 코드 삭제하고 register-club 의 ActivityReportForm을 사용한 이유가 있을까요?
ActivityReportForm 컴포넌튼는 atomic으로 되어 있기도 하고 동아리등록에서만 사용하는걸로 알고있어서요 (ui가 대표동아리 관리쪽이랑 다름, section Title 같은 것들) 
뭔가 이렇게 formCtx를 props로 전해주는 것이 이상해 보여서요 (이러면 form의 타입을 잡지 못해서 FormController의 name에 이상한 값 들어가도 컴파일 에러 잡지 못함)
그리고 엄연히 다른 feature의 다른 페이지라 코드 중복이 발생하더라도 분리하는 것이 좋아보여요 ActivityReportForm 사용하는 상위 useForm 찾아보니 동아리등록쪽에서 ApiAct007RequestBody 타입으로 정의되어 있던데 아무리 ApiAct003RequestBody 랑 속성 이름이 거의 같다고 해도 api에서 다른 api로 분리한 이상 유지보수를 위해서라도 따로 정의하는게 좋아보입니다..!!

2024-12-02 13:50 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
> +        <ActivityReportForm
엉 마자 사실 동아리 등록 쪽 폼 그대로 쓰는거보단 복제해서 쓰거나 하는 게 맞긴 할듯???? 동윤아 고쳐줘

2024-12-21 16:25 UTC, merged