1229 impl mee007 009 011
academic-relations/ar-002-clubs pull request #1232
Opened 2024-11-27 04:09 UTC by oRE-o

# 요약 \*

It closes #1229 
MEE 007, 009, 011 API를 구현하였습니다.
interface / Controller / repository / service 모두 구현했습니다.

그리고 중간에 Mapping 테이블을 다루는 부분에서 둘이 나누어 구현하다 보니 약간 다른 점이 존재했는데 질문드리고싶네용

# 스크린샷

# 이후 Task \*

MEE 006~011의 Req/Res의 구조를 조금 리팩토링하고 구조를 단일화 시키는 것은 어떨지..!
- 없음

2024-11-27 07:52 UTC, Engineer-JJHaMa requested changes
👍 수고했습니다! 코멘트 확인하고 수정 부탁해요~

2024-11-27 07:52 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/agenda/agenda.controller.ts
> +  @Post("/executive/meetings/meeting/:meetingId/agendas")
❗ Post가 아니라 Get인것 같아요. 혹시 테스트중에는 문제가 없었나요?

2024-11-27 07:52 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.repository.ts
> +          .then(result => {
❓ 여기선 soft deletion을 필터링할 필요가 없나요?

2024-11-27 07:52 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/agenda/agenda.controller.ts
> +      param,
❗ 컨벤션에 맞지 않는것 같아요. 확인해주세요!

2024-11-27 07:52 UTC, Engineer-JJHaMa commented on packages/api/src/feature/meeting/meeting.repository.ts
> +        meetingAgendaEntityType: 1, // Entity type is fixed to 1
💊 EntityType이 무엇인지 Enum을 통해 정의하고 주석이 있으면 이해하기 편할거 같아요

2025-01-04 10:00 UTC, oRE-o commented
말씀주신 내용 모두 수정하고자 했습니다.
특히 더 추가한 내용으로는 Entity Type이 뭔지 enum을 설정해두었습니다.

PR을 하고 오래 방치해서 죄송합니다..!! ㅠㅠ

2025-01-08 13:57 UTC, Engineer-JJHaMa approved these changes
dev와 싱크 맞추었어요~

2025-01-08 13:58 UTC, merged