Add onClick to Label
academic-relations/ar-002-clubs pull request #128
Opened 2024-05-09 11:47 UTC by predict-woo

# 요약 \*

It closes #97 

# 스크린샷

# 이후 Task \*

- 없음

2024-05-10 15:10 UTC, wjeongchoi approved these changes
clickable type 관련해서 코멘트 남겼는데 확인해주세요!

2024-05-10 15:10 UTC, wjeongchoi commented on packages/web/src/common/components/Forms/_atomic/Label.tsx
> +  type?: "default" | "clickable";
default / clickable로 type을 나누는 것보다는 clickable boolean을 넣는건 어떨까요? `type === "clickable"`을 그냥 `clickable`로 쓸 수 있어서 좋을 것 같아요

2024-05-10 15:10 UTC, wjeongchoi commented on packages/web/src/common/components/Forms/_atomic/Label.tsx
> +const StyledLabel = styled.label<{ type: LabelProps["type"] }>`
interface & const 순서 바꿔주세용

2024-05-11 11:49 UTC, Engineer-JJHaMa reviewed
궁금한 것만 질문해두었고, 나머지는 @wjeongchoi 님이 잘 체크해주셔서 굳입니다!

2024-05-11 11:49 UTC, Engineer-JJHaMa commented on packages/web/src/common/components/Forms/_atomic/Label.tsx
> +  <StyledLabel type={type} onClick={type === "clickable" ? onClick : () => {}}>
❓ onClick에 조건에 따라 함수를 제공할 때, 비어있는 함수  `() => {}`를 이용하는 것과 `undefined`를 이용하는 것의 차이가 있나요? 검색해봐도 잘 안나오는데, 빈 함수가 호출되는 것 외에 렌더링 등의 차이는 전혀 없는지 궁금해요

2024-05-12 15:29 UTC, babycroc requested changes
오.. 근데 이걸 어디에 쓰나요(????)

연결된 이슈를 보면 form의 label을 clickable하게 만드는 게 아니고 
checkbox나 radio의 label(사실 option이 더 맞는 말이겠군)을 clickable하게 해달라는 말이었습니다!! ㅎㅎ

혹시 제가 모르는 다른 의도가 있었던걸까(?) 앞으로 이슈 네이밍을 좀 더 잘해볼게요 🫠

2024-08-03 08:58 UTC, closed without merging

2024-08-03 08:58 UTC, babycroc commented
요거 close할게요~