139 fix ClubTypeEnum and add isParmanent
academic-relations/ar-002-clubs pull request #140
Opened 2024-05-10 17:51 UTC by Engineer-JJHaMa

# 요약 \*

CLB001, 002, 003 API의 response 수정에 따른 변화 적용입니다.
변경 이후 정상작동을 확인한 feature는 다음과 같습니다.
- clubs
- my
- clubDetails
만약 이외의 추가적으로 club API를 활용하는 feature가 있다면, 추가 수정하도록 하겠습니다.

It closes #139 

# 스크린샷

# 이후 Task \*

- 없음

2024-05-12 14:42 UTC, babycroc requested changes
코드에는 문제가 없어 보이는데 

`/clubs`에서 상임동아리가 맨 먼저 오게끔 하는 sorting logic에 반영이 안되어 있는 것 같습니다
요거만 고치고 다시 review 요청해주세요

2024-05-12 14:42 UTC, babycroc commented
추가로 merge conflict도 같이 해결한 뒤에 리뷰 요청해주세요

2024-05-12 14:46 UTC, wjeongchoi commented
> 추가로 merge conflict도 같이 해결한 뒤에 리뷰 요청해주세요

아마 이건 conflict 부분 (P_B 중복) 지우면 해결될거에요

2024-05-13 01:15 UTC, babycroc commented
@Engineer-JJHaMa [슬랙](https://sparcs.slack.com/archives/C06RTP91S3H/p1715562607662609)에도 물어봤는데 보니까 그거 때문에 타입 에서가 나더라고요 이것도 해당 PR에서 같이 고쳐서 올려주실 수 있나요?
<img width="1038" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/33417582/3d535590-06a6-4a44-ab28-8dc4ccaa9fd4">

2024-05-13 11:41 UTC, Engineer-JJHaMa commented
요청주신 사항 전부 반영했습니다!
- 정렬 로직에 isPermanent를 고려하는 부분을 추가했습니다.
- 최신 dev 브랜치 로컬에서 머지하여 충돌 전부 해결했습니다.
- 회원수 카운트와 관련된 변수를 totlaMemberCnt로 통일하여 타입 에러를 없앴습니다.

2024-05-13 11:43 UTC, babycroc approved these changes
LGTM

2024-05-13 11:43 UTC, merged