Create Table component and create activity report page
academic-relations/ar-002-clubs pull request #173
Opened 2024-05-16 14:01 UTC by predict-woo

# 요약 \*

It closes #116

# 스크린샷

# 이후 Task \*

- 없음

2024-05-23 20:12 UTC, predict-woo commented
![Screenshot 2024-05-24 at 05 11 31](https://github.com/academic-relations/ar-002-clubs/assets/63383967/a7f3d364-980b-40ff-8d4b-3d371c3b837e)

es-hangul을 이용한 정교한 한국어 이름 검색

2024-05-23 20:14 UTC, predict-woo commented
![Screenshot 2024-05-24 at 05 13 08](https://github.com/academic-relations/ar-002-clubs/assets/63383967/50a917ec-a68c-4d4b-9d39-ff1e78c26b07)
저는 개인적으로 전체선택 버튼보다 헤더에 체크박스를 추가하는건 어떨가 싶습니다! 혹시 고려후에 전체 선택 버튼이 더 낫다면 다시 변경하겠습니당

2024-05-23 20:18 UTC, predict-woo commented
![Screenshot 2024-05-24 at 05 18 01](https://github.com/academic-relations/ar-002-clubs/assets/63383967/bb806443-1dfb-4a98-b9be-aa59102200de)
Selection에 따른 색상 변경

2024-05-23 20:19 UTC, predict-woo commented
![Screenshot 2024-05-24 at 05 18 35](https://github.com/academic-relations/ar-002-clubs/assets/63383967/22a5135e-9835-45ed-a417-a5d84f1c6bcc)
필터링해도 Selection이 사라지지 않음

2024-05-23 20:34 UTC, predict-woo commented
![Screenshot 2024-05-24 at 05 33 36](https://github.com/academic-relations/ar-002-clubs/assets/63383967/a3d45d4e-02cd-457a-9f3c-a3a567821436)
검색이 이상하면 비어있어서 디자인이 필요할 수도 있을 것 같습니다.

2024-05-23 21:07 UTC, predict-woo commented
DateRangeInput 는 state 없이는 사용할 수 없어서, api가 완성되어 interface 연결하기 전까지는 comment out 해두겠습니다

2024-05-24 03:09 UTC, predict-woo commented
![image](https://github.com/academic-relations/ar-002-clubs/assets/63383967/8c16d661-2ba7-47ce-88ef-de2596425038)


Participants의 ordering을 해주는 핫픽스가 있었습니다

2024-05-24 03:25 UTC, predict-woo commented
![image](https://github.com/academic-relations/ar-002-clubs/assets/63383967/bcd4bf67-8c8b-4b5b-9424-6518e94f9724)
비어 있을때 메시지를 표시하는 emptyMessage 옵션을 Table 에 추가했습니다.

2024-05-24 03:30 UTC, babycroc requested changes
오 완전 신기한 거 많고 tanstack table 괜찮네ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 
역시 상우는 멀 많이 가져오는군 좋아용
코멘트 쭉 함 확인해줘!!

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/features/activity-report/components/NewActivityReportList.tsx
> +        <Tag color={getStatusTagColor(info.getValue())}>{info.getValue()}</Tag>
요기는 다른 `getStatusTagColor`를 정의해서 먹여줘야 할거야 태그 리스트가 달라서

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/features/activity-report/components/PastActivityReportList.tsx
> +        <Tag color={getStatusTagColor(info.getValue())}>{info.getValue()}</Tag>
요것두

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/features/activity-report/components/PastActivityReportList.tsx
> +      </Typography>
거의 아무도 눈치 못 챈 놀라운 점: 이거 색깔 gray600임

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/features/activity-report/components/NewActivityReportList.tsx
> +      </Typography>
요것두ㅎㅎ

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/features/clubs/frames/ClubsSectionFrame.tsx
>        />
엇 요것두 다시 `FoldableSectionTitle` 사용하게끔 바꿔주세용

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/features/activity-report/frames/ActivityReportMainFrame.tsx
> +          { name: "활동 보고서", path: "/activity-report" },
```suggestion
          { name: "활동 보고서", path: "/manage-club/activity-report" },
```

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/common/components/FoldableSectionTitle.tsx
> +  const openHandler = () => setOpen(!open);
오 이거 넣는 것도 나쁘지 않아 보이는군.. (나는야 팔랑귀)
다른 `FoldableSectionTitle` 사용한 곳에는 확실히 영향이 없나?

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/common/components/Icon.tsx
혹시 이거 넣은 이유가 뭔가요? 지금 쓰이는 곳 없어보이길랭

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/common/components/FoldableSection.tsx
옹 이것두 빼놨군 좋네
다만 걱정되는 부분은 `FoldableSection`이랑 `FoldableSectionTitle`이랑 이름이 넘 비슷해서 머가먼지 헷갈릴까봐.. 
흠 그건 어케 하면 좋으려나

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/features/activity-report/frames/ActivityReportCreateFrame.tsx
> +          { name: "활동 보고서", path: "/activity-report" },
```suggestion
          { name: "활동 보고서", path: "/manage-club/activity-report" },
```

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/features/activity-report/frames/ActivityReportCreateFrame.tsx
> +            {/* <DateRangeInput label="활동 기간" /> */}
아 맞아 이건 디자인이 쬐끔 바뀔 수도 있어서 일단 작업 보류해둡시당

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/features/activity-report/frames/ActivityReportCreateFrame.tsx
> +  gap: 20px;
저게 다 간격이 20px가 아니고 60px 20px 섞여있어용 ㅎㅎ..
![image](https://github.com/academic-relations/ar-002-clubs/assets/33417582/81a25d19-c84a-4c08-807e-259d25b71fbb)

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/common/components/Toggle.tsx
엌 머야 아이콘 회전 짱신기해

2024-05-24 03:30 UTC, babycroc commented on packages/web/src/features/activity-report/components/SelectParticipant.tsx
> +    ),
checkbox center align이 안 맞아요
<img width="250" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/33417582/4b17220e-8cb9-4863-afa1-3f1a464dc8dc">

2024-05-24 03:33 UTC, predict-woo commented on packages/web/src/app/manage-club/activity-report/create/page.tsx
헉 이거 안바꿨네요

2024-05-24 03:34 UTC, babycroc commented
아 그리고 그 사이에 dev에 변경사항이 꽤 있었던 것 같아서 안했으면 머지 전에 pull 받아서 문제 없는지 확인해주세용

2024-05-24 03:35 UTC, predict-woo commented on packages/web/src/common/components/ClubCategoryTitle.tsx
이거 제가 사용하지는 않는데 clubs를 prop으로 받는 컴포넌트 이름이 FoldableSectionTitle로 디자인이랑 이름도 달라서 피그마랑 컴포넌트 이름을 일치시킨거긴 합니당

2024-05-24 03:36 UTC, predict-woo commented on packages/web/src/common/components/FoldableSection.tsx
그러면 하나로 합치고 isTitle 같은걸 옵션으로 줄까요?

2024-05-24 03:36 UTC, predict-woo commented on packages/web/src/common/components/Table copy.tsx
헉ㅜㅠㅠ 감사합니다

2024-05-24 03:37 UTC, predict-woo commented on packages/web/src/common/components/FoldableSectionTitle.tsx
> +  const openHandler = () => setOpen(!open);
다른 FoldableSectionTitle을 사용한 곳은 아마 제가 FoldableSectionTitle 이름을 ClubCategoryTitle으로 바꾸어서 그걸 사용하는걸로 리펙토링 되었을거에요

2024-05-24 03:38 UTC, babycroc commented on packages/web/src/common/components/ClubCategoryTitle.tsx
오잉 아 디자인이 다른거엿군 그럼 일단 냅둬도 될듯

2024-05-24 03:39 UTC, predict-woo commented on packages/web/src/common/components/ClubCategoryTitle.tsx
엥 잠시만 이거 제가 pr 시작했을때는 저 컴포넌트가 없었던 걸로 기억하는데 혹시 누가 만든건가요?

2024-05-24 03:40 UTC, babycroc commented on packages/web/src/common/components/FoldableSectionTitle.tsx
> +  const openHandler = () => setOpen(!open);
아하 그럼 dev pull해서 최신 상태랑도 맞는지만 확인하면 그렇게 냅두죠

2024-05-24 03:41 UTC, predict-woo commented on packages/web/src/common/components/Table/TableCell.tsx
> +`;
이거는 원래 html상 table header는 <th> 태그를, table body는 <td> 태그를 사용해야 하기에 아래 CommonCellBodyWrapper을 복사해온 다음에 td만 th로 바꾸었습니다.

2024-05-24 03:41 UTC, babycroc commented on packages/web/src/common/components/FoldableSection.tsx
오..? 아 근데 그럼 하나의 컴포넌트가 너무 커질 것 같은디 흠 그냥 냅둬보자 사람들 헷갈리면 그때 바꾸지머

2024-05-24 03:41 UTC, predict-woo commented on packages/web/src/features/activity-report/components/NewActivityReportList.tsx
> +        <Tag color={getStatusTagColor(info.getValue())}>{info.getValue()}</Tag>
감사합니당

2024-05-24 03:42 UTC, predict-woo commented on packages/web/src/features/activity-report/components/PastActivityReportList.tsx
> +        <Tag color={getStatusTagColor(info.getValue())}>{info.getValue()}</Tag>
이거 혹시 태그 이름과 색깔 정리해둔 곳이 있을까요? 어떻게 색상을 지정해야 하는지를 잘 모르겠어서요! status 같은게 이름이랑 같이 백에서 날라오나요?

2024-05-24 03:43 UTC, babycroc commented on packages/web/src/common/components/ClubCategoryTitle.tsx
우정이가 최근에 만들엇거덩
clubcategorytitle 리팩토링 겸...
그래서 최신 dev 받아와서 확인해봐야할거같아
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-05-24 03:44 UTC, babycroc commented on packages/web/src/common/components/Table/TableCell.tsx
> +`;
마자마자 (사실 같은 이유로 버튼 컴포넌트도 div-> button으로 바꾸고 싶긴 함.. 이슈 만들어놔야겟다 ㅎ)

2024-05-24 03:46 UTC, babycroc commented on packages/web/src/features/activity-report/components/PastActivityReportList.tsx
> +        <Tag color={getStatusTagColor(info.getValue())}>{info.getValue()}</Tag>
오 정리해둔 곳은 없고 그냥 피그마에 이렇게 만들어둔거 사람들이 알아서 가져가서 쓰는듯
![image](https://github.com/academic-relations/ar-002-clubs/assets/33417582/2d3d489e-449d-4cc0-b72d-4fd8a967c93e)

사실실 태그가 좀 많아져서.. color mapping 정보랑 util 함수를 따로 만들어서 import해서 써도 좋겠다는 생각이 들긴 하네용..
(이건 이번 pr에서 하지는 말고 별도로 이슈를 만들어둘게용)

2024-05-24 03:50 UTC, predict-woo commented on packages/web/src/common/components/FoldableSectionTitle.tsx
> +  const openHandler = () => setOpen(!open);
이부분 다른 분과 변경사항이 겹친거 같은데 상황 파악이 제대로 안되어서요ㅜㅠ
제가 한건 기존 FoldableSectionTitle -> ClubCategoryTitle 변경
- 이유는 clubs를 prop으로 받는걸 FoldableSectionTitle과 같은 공용 컴포넌트로 이름짓는게 이상했고
- 피그마에도 ClubCategoryTitle로 되어있어서 입니다.
그리고 FoldableSectionTitle과 FoldableSection을 새로 만들었습니다.

2024-05-24 03:56 UTC, predict-woo commented
이미 dev를 머지해서 괜찮을 것 같습니다.

2024-05-24 04:02 UTC, predict-woo commented on packages/web/src/features/clubs/frames/ClubsSectionFrame.tsx
>        />
근데 얘는 clubList를 prop으로 받는데 FoldableSectionTitle은 공용 컴포넌트라 clubList를 사용하지 않아서 혹시 이걸 어떻게 수정하는게 좋을까용

2024-05-24 04:03 UTC, predict-woo commented on packages/web/src/common/components/Icon.tsx
styled-components 가 스타일링을 하려면 className을 prop으로 받아주어여 합니다 지금 이거는 그 아이콘 돌리는거 스타일 넘겨주느라 추가했을거에용

2024-05-24 04:04 UTC, babycroc commented on packages/web/src/features/clubs/frames/ClubsSectionFrame.tsx
>        />
그거 우정이가 리팩토링하면서 고친거 dev에 머지되어 있을텐데???
https://github.com/academic-relations/ar-002-clubs/blob/dev/packages/web/src/features/clubs/frames/ClubsSectionFrame.tsx#L35-L42

2024-05-24 04:08 UTC, babycroc commented on packages/web/src/common/components/FoldableSectionTitle.tsx
> +  const openHandler = () => setOpen(!open);
`ClubCategoryTitle`였던 이유는 clubs 페이지를 제일 처음에 디자인했기 때문 -> 네이밍이 그 페이지에 맞게 붙여졌고 이후 제가 다른 페이지 디자인할 때 아무 생각 없이 가져다 써서 그래요ㅋㅋ큐큐ㅠㅠ
피그마에서도 이름 바꿔두겠습니다

만약 clubs쪽에서 `ClubCategoryTitle `를 만들어 사용하고 싶다면 상관은 없음 (대신 `FoldableSectionTitle `을 wrapping해서 가져가는 형식이지 않을까??) 근데 무의미할 것 같아서 원래 있던 것을 빼버리기로 했던 것 같아요

2024-05-24 04:11 UTC, predict-woo commented on packages/web/src/features/clubs/frames/ClubsSectionFrame.tsx
>        />
엥 이미 dev머지했는데 머지????

2024-05-24 04:12 UTC, predict-woo commented on packages/web/src/features/clubs/frames/ClubsSectionFrame.tsx
>        />
이거 자동머지가 뭔가를 망쳐둔거 같은데 읽어보면서 수정할게요

2024-05-24 04:13 UTC, babycroc commented on packages/web/src/features/clubs/frames/ClubsSectionFrame.tsx
>        />
우잉 그거 좀 많이 힝이군 :sad_blob:

2024-05-24 05:54 UTC, babycroc commented on packages/web/src/features/activity-report/frames/ActivityReportCreateFrame.tsx
> +  gap: 20px;
@predict-woo 이거 안됏엉
FoldableSectionTitle랑 아래 outline card 사이는 20px로 해주세요

2024-05-24 05:59 UTC, babycroc approved these changes
그 gap 간격 바꾸는 것 + 코멘트 하나만 반영하고 바로 머지해도 좋을 것 같아요~~ 왕고생해따

2024-05-24 05:59 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
> +        <Typography type="p">
미안 요것두 회색으로 바꿔줭

```suggestion
        <Typography type="p" color="GRAY.600">
```

2024-05-24 08:34 UTC, merged