feat(notice): implement '/notice' page
academic-relations/ar-002-clubs pull request #18
Opened 2024-03-17 06:00 UTC by Engineer-JJHaMa

# 요약 \*

It closes #14 

# 스크린샷

<img width="1466" alt="notice page implementation by hama" src="https://github.com/academic-relations/ar-002-clubs/assets/69956347/1a988306-7663-4d86-acb4-55144a691a07">

# 이후 Task \*

- 없음

2024-03-17 06:07 UTC, babycroc commented
허걱 엄청나게 빠르시군요 얼렁 보께요

2024-03-17 06:52 UTC, Engineer-JJHaMa commented
일단 어느정도 완성이 된 것 같아서 draft 먼저 올려두어요. axios mockup 완성되면 적용해서 완성하겠습니다!

2024-03-20 08:03 UTC, babycroc requested changes
일단 한 번 쭉 보고 코멘트 달았어요!! 이것저것 자잘하게 말한 게 많은 것 같긴 하네요 💫 
작동은 아주 잘하네요 고생하셨습니다ㅎㅎㅎ 💯 🎊 
자잘한 수정사항들 + 더 하셔야 한다고 했던 작업 진행해서 다시 리뷰 요청해주세요~~ 🚀 

+ 작동하는 거 보니까 pagination number에 width를 안 주니까 highlight되면서 width 바뀌면서 미세하게 조정이 일어나서.. 숫자 무관 width height 모두 20px로 고정이게끔 피그마 수정해뒀어요 이것두 반영해주시면 매우매우 감사할 것 같습니다아ㅏ!!!

2024-03-21 11:24 UTC, babycroc commented
@Engineer-JJHaMa 아 맞다 지호랑 논의해본 결과 interface 정의들 다 파일 위쪽으로 빼기로 해서 그것도 고쳐주세요!!!

2024-03-21 14:14 UTC, Engineer-JJHaMa commented on packages/web/src/features/notice/frames/NoticeListAndPagenationFrame.tsx
> +  height: 651px;
넵 일단 fill로 고치겠습니다!

2024-03-21 14:14 UTC, Engineer-JJHaMa commented on packages/web/src/features/notice/frames/NoticeListAndPagenationFrame.tsx
헉 수정할게요!

2024-03-21 14:15 UTC, Engineer-JJHaMa commented on packages/web/src/features/notice/frames/NoticeListAndPagenationFrame.tsx
> +  const [noticeInfos, setNoticeInfos] = useState<Array<NoticeInfo>>([]);
state의 타입을 명시적으로 적어두고 싶어서 넣어두긴 했어요 ㅎㅎ

2024-03-21 14:17 UTC, Engineer-JJHaMa commented on packages/web/src/features/notice/frames/NoticePageMainFrame.tsx
> +    <PageTitle>동아리 목록</PageTitle>
으아악..

2024-03-21 14:21 UTC, Engineer-JJHaMa commented on packages/web/src/constants/noticeList.ts
👍 👍

2024-03-21 14:23 UTC, babycroc commented on packages/web/src/features/notice/frames/NoticeListAndPagenationFrame.tsx
> +  const [noticeInfos, setNoticeInfos] = useState<Array<NoticeInfo>>([]);
저도 원래 그렇게 짜긴 했었어요 냅둬도 상관없어요ㅎㅎㅎㅎ

2024-03-22 12:18 UTC, Engineer-JJHaMa commented on packages/web/src/features/notice/componenets/NoticeListItem.tsx
> +  width: calc(100% - 84px - 20px);
해결했습니다!
```css
flex-grow: 1;
flex-shrink: 1;
overflow: hidden;
```
세가지 속성을 동시에 줘야 하는 것 같아요!

2024-03-22 12:23 UTC, Engineer-JJHaMa commented on packages/web/src/features/notice/componenets/NoticeListItem.tsx
> +`;
추가했습니다!

2024-03-22 12:27 UTC, Engineer-JJHaMa commented on packages/web/src/features/notice/componenets/NoticeList.tsx
> +  height: calc(100% - 41px);
아래 pagination 영역 높이랑 gap을 뺀 수치인데, 이것도 flex-grow랑 shrink 이용해서 맞춰볼게요!

2024-03-25 13:11 UTC, closed without merging