feat: implement '/clubs/[id]' page
academic-relations/ar-002-clubs pull request #20
Opened 2024-03-18 06:36 UTC by wjeongchoi

# 요약 \*

It closes #15 

# 스크린샷

# 이후 Task \*

- 없음

2024-03-18 16:00 UTC, wjeongchoi commented
mock data 사용해서 UI는 완성해두었습니다! 백 연결 관련 다른 작업 끝나면 마저 완성하겠습니다.

2024-03-18 16:01 UTC, wjeongchoi commented
그리고 동아리 설명 카드 반응형이 동아리 정보 카드랑 조금 다르게 되어 있어서 둘중 어디에 맞춰야 하는지 궁금합니다 @babycroc

2024-03-20 08:21 UTC, babycroc commented
@wjeongchoi 좋은 질문입니당
왜 그 얘기가 나왔는지 알 것 같은데, 해결책을 가장한(?) 추가 태스크를 만들어 왔어요
https://github.com/academic-relations/ar-002-clubs/issues/15#issue-2186263762 <- 이슈에서 확인해주시면 될 것 같습니다!!!

2024-03-20 09:23 UTC, babycroc requested changes
쭉 함 봤는데 컴포넌트랑 프레임 잘 나누셨네요!! :D
코멘트 남긴 거 쭉 함 봐주세용 + 할일을 추가로 만들어서 이슈에 달아뒀어요ㅎㅎㅎ

2024-03-21 14:20 UTC, babycroc commented
@wjeongchoi 넹~

2024-04-04 14:04 UTC, babycroc approved these changes
쪼아용~~~ 고생했습니다ㅏ아
코멘트 하나 있는데 그것만 고치고 머지하시면 될 것 같습니다ㅏ

2024-04-04 14:09 UTC, merged