233 common space connect backend
academic-relations/ar-002-clubs pull request #258
Opened 2024-05-24 17:16 UTC by predict-woo

# 요약 \*

It closes #233 

# 스크린샷

# 이후 Task \*

- 없음

2024-07-02 09:40 UTC, babycroc requested changes
작동은 잘 하는 것 같은뎅

(기억이 안나겠지만..) 혹시 남았던 투두 같은 거 있음 한 번 정리해주면 좋을 것 같궁
그보다 dev merge를 한 번 해보자 어마무시하게 많이 바뀌었을 것 같아서 ㅇㅁㅇ
+주석 친 부분들 안 중요한거면 지워주세요~~

dev merge 함 한 담에 (rebase가 나을수도 있겠다는 생각이 들긴 함) 다시 리뷰 요청해죵

2024-07-03 01:13 UTC, jooyeongmee requested changes

2024-07-03 01:13 UTC, jooyeongmee commented on packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
> +  }, [selectedValue, setCommonSpace]);
dependency가 일부 빠진 것 같습니다. `data, commonSpace` 추가 부탁드려요

2024-07-03 01:13 UTC, jooyeongmee commented on packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
>    }, [selectedValue, setCommonSpace]);
여기도 dependency 추가 부탁드려요! `commonSpace, data?.commonSpaces`

2024-07-03 01:13 UTC, jooyeongmee commented on packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/index.tsx
>    }, [nextEnabled, step, setStep]);
handleSubmit 추가 부탁드립니닷

2024-07-03 01:13 UTC, jooyeongmee commented on packages/web/src/common/components/Timetable/_atomic/TimetableTable.tsx
여기도 dependency 많이 빠진 것 같은데 추가 부탁드립니다! 
eslint 중에 `'plugin:react-hooks/recommended',` 이라고 이런거 체크해주는 친구가 있는데 혹시 요거 추가하면 어떨까요?
@babycroc

2024-07-06 16:58 UTC, predict-woo commented
머지하긴 했는데 아직 mock 수정사항이 있는걸로 기억해서 완료하고 리뷰 요청하겠습니다!

2024-07-07 15:56 UTC, predict-woo commented on packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
> +  }, [selectedValue, setCommonSpace]);
앗 data를 빼먹었군요! commonSpace는 들어가면 루프가 걸릴거 같은데 혹시 아닐까요?

2024-07-08 00:27 UTC, babycroc commented on packages/web/src/common/components/Timetable/_atomic/TimetableTable.tsx
very good idea 
eslint 규칙 추가할게용

2024-07-08 00:58 UTC, babycroc approved these changes
작동은 잘 하는 것 같군!

리뷰하는 김에 추후에 고쳐야 할 자잘한 todo들도 함께 적어둘게요 (별도 이슈에서 작업해도 ㄱㅊ)
- 신청자 전화번호는 default로 백엔드에서 가져온 값을 넣되, 수정 가능해야 함
- second frame에서 "신청 시간" font-weight medium

- "예약 정보 입력" 페이지에서 "기본 정보 입력" 페이지로 돌아갈 때 ("이전" 버튼 눌러서) 입력했던 정보가 남아 있어야 함
  - 다만 "예약 정보 입력" 페이지에 입력된 정보가 있을 경우 (선택된 공용공간이 있음) "이전" 버튼을 눌렀을 때 "초기화 ㄱㅊ?" 모달이 뜨면 좋을 것 같아요 (대여사업 flow 참고)
- "최종" 페이지에서 "예약 정보 입력" 페이지로 돌아갈 때 ("이전" 버튼 눌러서) 입력했던 정보가 남아 있어야 함

2024-07-08 00:58 UTC, babycroc commented on packages/web/src/features/common-space/service/getCommonSpaceUsageOrders.ts
> +// import { addWeeks, startOfWeek } from "date-fns";
```suggestion
```

2024-07-08 01:01 UTC, babycroc commented on packages/web/src/common/components/Timetable/_atomic/TimetableTable.tsx
@predict-woo  https://github.com/academic-relations/ar-002-clubs/pull/366 -> 여기에 해당 eslint 규칙 추가한 작업 올려놨는데 warning 고치는 건 (저거 머지된 다음에) 추후에 한 번에 처리해도 될 것 같아서 영미가 말한 정도만 한 번 봐주고 빠진 건 나중에 고쳐봅시당~

2024-07-08 14:07 UTC, predict-woo commented
@babycroc @jooyeongmee @wjeongchoi 리뷰해주세요ㅜㅠ

2024-07-08 15:28 UTC, predict-woo commented on packages/web/src/features/common-space/service/getCommonSpaceUsageOrders.ts
> +// import { addWeeks, startOfWeek } from "date-fns";
뒤에 3개 테스크는 조금 길어질 것 같아서 따로 분리하겠습니다!

2024-07-09 00:48 UTC, merged