feat: create clubs/my page
academic-relations/ar-002-clubs pull request #27
Opened 2024-03-20 16:47 UTC by jooyeongmee

# 요약 \*

It closes #13 

# 스크린샷

<img width="1511" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/89931104/a1c52849-64c6-46fe-a168-871bfff093bd">
<img width="1507" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/89931104/fac942e1-c0a2-4b31-8a13-36569f5d4159">

# 이후 Task \*
- 없음

# 참고사항 

1. 제공받은 mockData 중 clubs 데이터가 정의되어 있는 ClubsInfo와 변수 이름이 맞지 않아 mockData 수정했습니다.
2. 이미 만들어져 있는 DivisionSectionTitle, ClubsSectionFrame 을 재사용하면 좋겠다고 생각하였고 DivisionSectionTitle 옆의 length 부분이 기존에는 default로 들어가 있어 showLength?: boolean 속성을 추가하여 DivisionSectionTitle 에서 length 추가 여부를 선택할 수 있도록 수정하였습니다 (showLength 값은 default = true로 넣었습니다)
3. RawData의 타입 정의 할 때 ClubsRawData의 타입도 필요하여 기존의 clubs.types.ts에 RawClubsData 타입도 export 하게 수정하였습니다.

혹시 이 수정사항들이 문제다 된다면 코멘트 달아주시면 다시 수정해보겠습니다:)

2024-03-20 18:03 UTC, babycroc requested changes
좋아요!! 잘 작동하네요 👍 
이미 있는 타입이나 컴포넌트를 최대한 재사용하려고 하는 거 좋은 것 같아요!!! 
코멘트 단 것만 한 번 확인해주시구 review rerequest해주세요!!
늦은 시간까지 고생하셨습니다ㅎㅎㅎ

2024-03-21 07:28 UTC, jooyeongmee commented on packages/web/src/features/my/frames/MyPageMainFrame.tsx
> +          ))}
좋은 생각인것 같습니다! 반영하겠습니다~

2024-03-21 07:28 UTC, jooyeongmee commented on packages/web/src/features/clubs/components/DivisionSectionTitle.tsx
> +}> = ({ division, clubList, toggle, showLength = true, toggleHandler }) => (
넵 FoldableSectionTitle 좋은거 같아요~!!

2024-03-21 13:51 UTC, babycroc approved these changes
LGTM!

2024-03-21 13:52 UTC, merged