table component refactoring
academic-relations/ar-002-clubs pull request #349
Opened 2024-07-04 07:42 UTC by wjeongchoi

# 요약 \*

It closes #333 

# 스크린샷

# 이후 Task \*

- contents length가 pageLimit의 배수일 경우 마지막 빈 페이지 생기는 문제 해결
- div로 th 감싸는 문제 해결
- my service 이외의 table에도 확장하여 사용 가능할 것으로 보임

2024-07-04 13:53 UTC, babycroc requested changes
보니까 `topComment`에 들어가는 게 다 `contents.length`인 것 같은데
뭔가 디자인 consistency를 위해서는 그 위치는 항상 총 개수를 표시할 것 같아서요
string 타입의 `topComment` prop보다는 boolean 타입의 `showTotalCount` 아니면 number 타입의 `totalCount` 같은 게 더 적합하지 않을까..라는 생각이 들긴 합니다!! 

---

뭐 variation이 있다면 이 정도 `10개 / 100개`까지는 되겠다만 아직까지는 디자인에 그런 게 없을걸??
-> 은 정정할게요 회원 명단 검색 쪽에 `검색 결과 2명 / 총 50명` 이런 게 있긴 하네
-> 이 경우에는 default suffix는 '개'로 하되 '명'으로 바꿀 수 있게 해도 괜찮을 것 같아요

너무 말로만 해서 이해가 안갈까봐
```
interface TableProps {
  // 기존에 있던 prop들
  pageLimit?: number;        // 기본 10
  showTotalCount?: boolean;  // 기본 ???
  customUnit?: string;       // 기본 "개"
  // 흠냐 검색 결과 쪽은 잘 모르겠군 검색 결과 table을 통합하려 하지 말고 분리하는 것이 나을수도
}
```

이해 안가지? 나도 지금 헷갈려 DM 줭

글구 더 좋은 아이디어가 있다면 의견 남겨주세용

2024-07-04 18:38 UTC, wjeongchoi commented
> 보니까 `topComment`에 들어가는 게 다 `contents.length`인 것 같은데 뭔가 디자인 consistency를 위해서는 그 위치는 항상 총 개수를 표시할 것 같아서요 string 타입의 `topComment` prop보다는 boolean 타입의 `showTotalCount` 아니면 number 타입의 `totalCount` 같은 게 더 적합하지 않을까..라는 생각이 들긴 합니다!!
> 
> 뭐 variation이 있다면 이 정도 `10개 / 100개`까지는 되겠다만 아직까지는 디자인에 그런 게 없을걸?? -> 은 정정할게요 회원 명단 검색 쪽에 `검색 결과 2명 / 총 50명` 이런 게 있긴 하네 -> 이 경우에는 default suffix는 '개'로 하되 '명'으로 바꿀 수 있게 해도 괜찮을 것 같아요
> 
> 너무 말로만 해서 이해가 안갈까봐
> 
> ```
> interface TableProps {
>   // 기존에 있던 prop들
>   pageLimit?: number;        // 기본 10
>   showTotalCount?: boolean;  // 기본 ???
>   customUnit?: string;       // 기본 "개"
>   // 흠냐 검색 결과 쪽은 잘 모르겠군 검색 결과 table을 통합하려 하지 말고 분리하는 것이 나을수도
> }
> ```
> 
> 이해 안가지? 나도 지금 헷갈려 DM 줭
> 
> 글구 더 좋은 아이디어가 있다면 의견 남겨주세용

이 컴포넌트로 다른 Table도 적용시키는걸 생각 중인데 말한 것처럼 `10개 / 100개` 이런게 생기는거 생각하면 지금처럼 텍스트 자체를 넣는게 좋을 것 같다고 생각해서 이렇게 개발했어요
텍스트 형식이 달라질 때 다른 table 컴포넌트를 만드는 걸 최대한 피하고 싶음

2024-07-06 13:47 UTC, babycroc reviewed
Hmm 좀 더 생각해볼게
당장 급한 건 아닌거 같아서 ㅇㅋ

2024-07-06 13:48 UTC, babycroc approved these changes

2024-07-06 16:51 UTC, merged