impl progressStatus
academic-relations/ar-002-clubs pull request #350
Opened 2024-07-04 10:45 UTC by wjeongchoi

# 요약 \*

It closes #335 
```
        <ProgressStatus
          labels={["신청 완료", "사용 대기"]} // 존재하는 label 목록
          status={[Status.Approved]} // 완료된 label의 상태 목록
          dates={[new Date()]} // 완료된 label의 날짜 목록
          infoText="사용 일시가 지나기 전까지 신청을 취소할 수 있습니다"
        />
```
# 스크린샷

# 이후 Task \*

- 반려 사유 작성이 존재하는 신청 상태의 경우 어떻게 처리할지

2024-07-05 13:21 UTC, babycroc requested changes
얘를 예시로 설명해볼게요
<img width="623" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/33417582/63969137-2bcd-4247-9a37-f57d10f2d1e1">

보면 공통적으로 어떤 구조냐면
1. "신청 상태" 텍스트
2. progress bar 같이 생긴거
3. (있을 수도 있고 없을 수도 있는) 밑에 부가 주저리주저리
이렇게 크게 3개로 나눌 수 있을 것 같아용

2는 `ProgressCheckSection`을 그대로 사용해도 될 것 같구
3은 코멘트에도 썼다시피 다 제각각일거라 123을 합친 최종 컴포넌트는 common으로 두기 어려울 수도 있겠다는 생각이 들엉

2024-07-05 13:21 UTC, babycroc commented on packages/web/src/common/components/ProgressStatus.tsx
> +    <Button style={{ width: "max-content" }}>신청 취소</Button>
여기에 이런 로직을 넣으면 되지 않을까

if status = 신청 then <infotext + 신청취소 button>
if status = 취소 then <></>
if status = 어쩌고저쩌고..

2024-07-05 13:21 UTC, babycroc commented on packages/web/src/common/components/ProgressStatus.tsx
> +  dates: Date[];
얘랑 얘는 길이가 같지 않아? 그래서 사실 prop 두개에 나눠서 전달받지 않고 묶여 있었으면 좋겠어 
그래야 둘이 길이가 다른 invalid한 input이 절대 안 주어지게끔

그리고 ㅗ이건 디비 쪽을 확인해보면 좋을 것 같은데, 
"신청 -> 반려 -> 반려 -> 승인 -> (수정으로 인한 재)신청 -> 승인"
의 경우에 모든 상태 정보를 다 들고 있을건지, 아니면 같은 상태일 경우 마지막 한 개씩만 들고 있을건지..

2024-07-05 13:21 UTC, babycroc commented on packages/web/src/common/components/ProgressStatus.tsx
> +    <Button style={{ width: "max-content" }}>신청 취소</Button>
근데 이건 funding progress랑 acf progress랑 등록 신청 progress랑 각각 다 제각각일거라, 
이렇게 하나의 ProgressStatus 컴포넌트로 정리하기는 어려울 것 같아서 그냥 각각
FundingProgressStatus / ACFProgressStatus / ... 
이렇게 나눠야 하지 않을까라는 생각

2024-07-05 20:00 UTC, wjeongchoi commented on packages/web/src/common/components/ProgressStatus.tsx
> +    <Button style={{ width: "max-content" }}>신청 취소</Button>
infoText가 있을 때만 info를 띄우는 걸로 하고
밑에 선택으로  <></> 이걸 넣을 수 있게 하면 컴포넌트로 처리할 수 있을 것 같다!
내가 manage-club 쪽 피그마를 다시 확인하지 않아서 생긴 일인듯

수정하고 re-request 할게용

2024-07-05 20:04 UTC, wjeongchoi commented on packages/web/src/common/components/ProgressStatus.tsx
> +  dates: Date[];
표에서 보여줄 마지막 하나씩만 들고 있는걸로 프론트에서 저 status에 넣을 때 처리해야 할듯

2024-07-07 14:50 UTC, babycroc approved these changes

2024-07-07 14:50 UTC, babycroc commented on packages/web/src/common/components/ProgressStatus.tsx
> +    {optional && optional}
왜 두번 들어간거징

2024-07-07 14:50 UTC, babycroc commented on packages/web/src/common/components/ProgressStatus.tsx
> +    {optional && optional}
아 난  바보야 이해했어 ㅋ쿠쿸ㅋ

2024-07-07 14:51 UTC, babycroc commented on packages/web/src/common/components/ProgressStatus.tsx
> +    {optional && optional}
근데 꼭 두번이 필요한 게 맞나?

2024-07-07 14:58 UTC, wjeongchoi commented on packages/web/src/common/components/ProgressStatus.tsx
> +    {optional && optional}
맞는말이야
그래서 고쳤어

2024-07-07 14:58 UTC, merged