add credits
academic-relations/ar-002-clubs pull request #383
Opened 2024-07-09 15:09 UTC by jooyeongmee

# 요약 \*

It closes #372 

# 리뷰 요청 사항
1. 빠진 부원 있는지 확인
2. 각자 이름, 닉네임, 직군 정보 맞는지 확인

# 질문
- hover 시 문구 변경 기능이 없는 것 같은데 혹시 이 이슈에서 같이 추가하는걸 의도하신걸까요? @wjeongchoi 

# 스크린샷
<img width="1197" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/89931104/ab65a987-cbca-4ca9-92b6-a0ca7a313d82">

# 이후 Task \*

- 없음

2024-07-09 15:15 UTC, babycroc commented
hover 시 문구 변경은 스포가 될 수 있으니 나중에 작업 넣는걸루 하쟝

2024-07-09 15:17 UTC, wjeongchoi commented
```
export interface Member {
  nickname: string;
  name: string;
  role: string;
  roleType: RoleType;
  comment?: string;
}
```

여기에 있는 comment에 텍스트를 달아야 호버가 작동합니다!

2024-07-09 15:24 UTC, jooyeongmee commented
오에 그러네 올리려했는데.. stash가 두개 생겨버렸군

2024-07-09 15:31 UTC, wjeongchoi commented
아 그리고 말록 프론트라서 그 부분 지워주세용

2024-07-13 21:58 UTC, wjeongchoi requested changes
<img width="547" alt="스크린샷 2024-07-13 오후 11 57 43" src="https://github.com/user-attachments/assets/22b804cd-41a5-4169-bd53-9b783d5e09d0">

여기 보면 봄/여름 margin-left가 다르게 들어간 것 같은데 확인하고 맞는 쪽으로 수정해주세요!

2024-07-15 15:26 UTC, wjeongchoi approved these changes
좋아용

2024-07-16 01:09 UTC, babycroc approved these changes

2024-07-16 01:09 UTC, babycroc commented on packages/web/src/features/credits/frames/CreditsMainFrame.tsx
> +            <MemberCardSection credit={credit} leftMargin={24} />
👍

2024-07-16 01:09 UTC, babycroc commented on packages/web/src/features/credits/components/MemberCardSection.tsx
> +  credit,
credits나 creditList 같은 복수임을 암시하는 단어로 바꾸장

2024-07-18 15:14 UTC, jooyeongmee commented on packages/web/src/features/credits/components/MemberCardSection.tsx
> +  credit,
흠 바꾸려다 문득 든 생각인데.. 요거 배열이 아니라 하나의 Credits 타입의 오브젝트인데 복수로 하면 이상하지 않을까? 
아래 사진에서처럼 전체 credits 리스트가 이름이 credits라 뭔가 좀 이상해 보여서!
<img width="305" alt="image" src="https://github.com/user-attachments/assets/c27e2f71-9996-431c-8a65-5f5731ac2877">

2024-07-20 16:27 UTC, babycroc commented on packages/web/src/features/credits/components/MemberCardSection.tsx
> +  credit,
어라 그러게...
SemesterCredit이라던가 먼가 그런 식의 단수로 바뀌는 게 나을 것 같네 ㅇ.ㅇ 같이 고쳐줄 수 있나?!

2024-07-21 15:06 UTC, babycroc approved these changes
💯

2024-07-22 01:08 UTC, merged