feat: chacha's credit
academic-relations/ar-002-clubs pull request #387
Opened 2024-07-10 04:10 UTC by ChaeyeonAhn

# 요약 \*

It closes #370 
코드 수정, commit, commit message convention, push, PR 올리는 것 등 전반적인 과정이 맞게 되었는지 피드백 해주시면 감사하겠습니다.

# 스크린샷

<img width="1053" alt="스크린샷 2024-07-10 오후 1 03 03" src="https://github.com/academic-relations/ar-002-clubs/assets/154397014/d0f85c41-cc79-4642-8734-14b12ad3a3db">

# 이후 Task \*

- 없음

2024-07-10 06:41 UTC, babycroc requested changes
코드 수정 
- 쪼아요

commit, commit message convention 
- 우리가 commit 형식 자동으로 확인하는 hook이 달려있어서, 커밋이 문제 없이 됐으면 적어도 clubs repo 규칙에는 문제가 없다는 뜻!
- 그리고 굳이 뭔가 첨언을 하자면 "commit message는 과거형 말고 현재형으로 써라"라는 규칙을 통상적으로 사용하는 것 같긴 합니당

push, PR 올리는 것 
- 조아요! 지금은 간단한 태스크라 커밋도 한개고 작업 호딱 하고 pr 여는 게 가능한데, 나중에 좀 더 시간이 걸리는 태스크를 하게 된다면 그때는 draft pr을 먼저 연 후에 작업 끝나면 ready for review로 pr의 상태를 바꾸는 것도 해보면 좋을 것 같아요! (나중에 다시 알려드릴게용ㅎㅎ) 
- 참고로 커밋이 한 개일때는 커밋이 그대로 pr 이름이 되는데 (여러개일때도 그랬나..??? 잘 기억이 안나는군) pr 이름도 기본으로 추천해주는 거 말고 스스로 작명(?)을 하면 좋을 것 같아요!!

- pr 설명에 `it closes #이슈넘버` <- 요거는 예약어(?) 같은 아이라 문장을 막 고치면 안돼요! (사실 사용 가능한 variation이 몇 개 있긴 해서 찾아봐도 좋을듯! [일단 암거나 함 가져와봤어요](https://yeoonjae.tistory.com/entry/Project-Github-PR-merge-%EC%8B%9C-issue-%EC%9E%90%EB%8F%99-close-%EB%B0%A9%EB%B2%95)) 아 그리고 한 pr에 이슈 여러개 달아두는 것도 가능!
저건 뭐냐면 이 pr이 close되었을 때 연결된 issue도 자동으로 close되게끔 해주는거구
- 스크린샷 넣는 곳에는 코드보다는 local에서 실행된 화면을 캡쳐해서 넣는 의도이긴 합니다!
FE의 경우 구현이 화면에 잘 보이나 확인하는 게 중요한데, 리뷰하는 사람이 매 번 코드를 pull 받아서 로컬에 돌려보는 게 오래걸림 + 조금 귀찮음ㅎㅎㅎㅎㅎ

+지금은 잘 되어 있는데 pr 만들 때 front-end 태그 달려 있는지, assignee = 본인, issue 잘 연결되어 있나, pr이 draft상태는 아닌지, reviewer 잘 요청됐나도 추가로 확인해주시면 되구 (많아보이지만 요건 하다보면 익숙해질거에요~~)

저희 정책이 리뷰 approve 한 개 이상 받으면 머지 가능
request changes 를 한 사람이 한 명이라도 있으면 그 사람이 재확인 후 approve해야 머지 가능
(참고로 리뷰 옵션은 다음과 같아요)
<img width="378" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/33417582/d4e02318-c36e-41c1-aba9-da6b569d0a6d">

내가 너무 생각나는대로 다 주저리주저리 써서 많긴 한데.. 지금 다 이해 안해도 됩니다!!!! 그냥 함 써봣어요.. ㅎㅎ (그리고 차차는 내가 이따만큼 알려줘도 소화를 잘 하더라구~)

지금은 연습 삼아서 제가 request changes로 리뷰를 submit해볼게요!
**PR리뷰 설명에 있는 스크린샷을 로컬에서 실행한 화면 스크린샷으로 바꿔보고 @babycroc 에게 다시 review re-request**를 해보시면 좋을 것 같습니다!!!

2024-07-10 07:14 UTC, ChaeyeonAhn commented
자세한 피드백 감사합니다ㅎㅎ 열씸히 참고하겠습니다!
고쳐서 재요청 드리겠습니다

2024-07-10 09:25 UTC, wjeongchoi approved these changes
코드 잘 찾아서 짰네용
자세한 설명은 도라가 다 해줬으니 저는 생략할게요
시간 여유 되면 `good first issue`도 하나 골라서 해보세요!

2024-07-11 09:04 UTC, babycroc approved these changes
늦게 확인해서 미안해ㅠㅠㅠ 조아용~~~~

2024-07-11 09:19 UTC, merged