#14 Impl Notice List Page - hama
academic-relations/ar-002-clubs pull request #40
Opened 2024-03-25 13:16 UTC by Engineer-JJHaMa

# 요약 \*

It closes #14

# 스크린샷
<img width="1470" alt="스크린샷 2024-03-25 오후 10 15 00" src="https://github.com/academic-relations/ar-002-clubs/assets/69956347/09154bf7-c77a-4141-8e78-7dd6c3f405cf">

# 이후 Task \*

- Date 관련 라이브러리 추가 결정하기

2024-03-26 15:41 UTC, UrWrstNightmare commented on packages/web/src/features/notice/services/mockupNoticeList.ts
/services/_mock/ 폴더 안에 넣어주시면 좋을 것 같습니다!
(mock 용도로만 내부에서 사용되는 파일임)

2024-03-28 11:33 UTC, babycroc requested changes
좋아요! flex layout하는 거 고생했습니다ㅏ 🙃
코멘트에는 없지만 지금 보니까 `features/notice/componenets` 폴더 이름에도 오타가 있어서 이것도 같이 고쳐서 올려주세요~~

2024-03-28 11:33 UTC, babycroc commented on packages/web/src/app/notice/page.tsx
> +export default Clubs;
저번에 `UseClientProvider`를 `layout.tsx`로 뻈어서 이제 매 페이지마다 추가하지 않으셔도 됩니다!!
추가로 export function name도 `Notice`로 바꿀게용

```suggestion
"use client";

import NoticePageMainFrame from "@sparcs-clubs/web/features/notice/frames/NoticePageMainFrame";

const Notice = () => <NoticePageMainFrame />;

export default Notice;
```

2024-03-28 11:33 UTC, babycroc commented on packages/web/src/features/notice/componenets/NoticeList.tsx
> +  border-color: ${({ theme }) => theme.colors.GRAY[200]};
사실 color도 그냥 한 속성에 같이 묶어서 작성해주면 좋을 것 같아요!! (다른 파일에서도 마찬가지로)

```suggestion
  border-bottom: 1px solid ${({ theme }) => theme.colors.GRAY[200]};
```

2024-03-28 11:33 UTC, babycroc commented on packages/web/src/features/notice/componenets/NoticeListItem.tsx
> +const NoticeTitleWrppaer = styled.div`
오타!

```suggestion
const NoticeTitleWrapper = styled.div`
```

2024-03-28 11:33 UTC, babycroc commented on packages/web/src/features/notice/componenets/NoticeListItem.tsx
> +      })}
오 이런 게 되는군요 신기하다 👀

2024-03-28 11:33 UTC, babycroc commented on packages/web/src/features/notice/componenets/NoticeListItem.tsx
> +  ${({ theme }) => theme.fonts.WEIGHT.MEDIUM}
```suggestion
  color: ${({ theme }) => theme.colors.BLACK};
```

2024-03-28 11:33 UTC, babycroc commented on packages/web/src/features/notice/componenets/NoticeListItem.tsx
> +  ${({ theme }) => theme.fonts.WEIGHT.MEDIUM};
```suggestion
  color: ${({ theme }) => theme.colors.BLACK};
  font-weight: ${({ theme }) => theme.fonts.WEIGHT.MEDIUM};
```

2024-03-28 11:33 UTC, babycroc commented on packages/web/src/features/notice/componenets/NoticePagination.tsx
> +`;
제가 pagination 디자인을 조금 고쳐서.. 요것두 그냥 같이 반영해서 넣어주세용

```suggestion
const WalkableIndex = styled.div`
  width: 20px;
  font-weight: ${({ theme }) => theme.fonts.WEIGHT.MEDIUM};
  font-size: 16px;
  line-height: 20px;
  color: ${({ theme }) => theme.colors.BLACK};
  text-align: center;
`;

const CurrentIndex = styled.div`
  width: 20px;
  font-weight: ${({ theme }) => theme.fonts.WEIGHT.MEDIUM};
  font-size: 16px;
  line-height: 20px;
  color: ${({ theme }) => theme.colors.PRIMARY};
  text-align: center;
`;
```

2024-03-28 13:49 UTC, Engineer-JJHaMa commented on packages/web/src/features/notice/componenets/NoticeListItem.tsx
> +      })}
저도 알고싶지 않았는데 ㅠㅠ 언능 Date formatting 라이브러리 추가해주세요!

2024-03-28 13:52 UTC, Engineer-JJHaMa commented on packages/web/src/app/notice/page.tsx
> +export default Clubs;
확인했습니다!

2024-04-04 09:06 UTC, Engineer-JJHaMa commented
### 24.04.04 수정사항
1. 코드 리뷰 사항 적용하기
2. 인터페이스 신규 컨벤션 적용하기
3. 서비스 신규 컨벤션 적용하기

2024-04-05 04:16 UTC, babycroc approved these changes
좋아요!!! 된 것 같습니당 고생했어요

2024-04-05 04:51 UTC, merged