Typography component refactoring
academic-relations/ar-002-clubs pull request #426
Opened 2024-07-17 06:11 UTC by jinhyeonkwon

…raphy with fs, lh, fw : except when type='span'

# 요약 \*

It closes #314

`Typography` (그리고 이것을 wrap하여 만들어진 `StyledTypography`) 컴포넌트의 스타일을 설정할 때, `type` 속성을 사용하는 경우와 `fs`, `lh`, `fw` 속성을 사용하는 경우가 혼재되어 있습니다. `TypographyProps` 타입 정의는 이 두 가지 경우 모두 허용합니다.
현재 `type`을 사용하고 있는 부분을 모두 `fs`, `lh`, `fw` 로 바꾸면서 `TypographyProps` 타입 정의에서 `TypographyPropsWithType`을 제거하고자 합니다.

## 현재 진행 상황
- `type="span"` 인 경우를 제외하고 모두 교체 완료하였습니다.
- 아직 모든 변경 사항에 대하여 실제 보이는 style이 같은지 테스트하지는 않았습니다. 주요한 몇 component에서 같은 style로 화면에 보이는 것을 확인했습니다.
- `type="span"`이 들어간 경우는 `IconButton.tsx`가 유일한데, 아래의 사유로 어떤 style로 대체할지 정하지 못하였습니다. 따라서 피드백을 먼저 요청 드립니다.
  -  `Typography.tsx` 내에서 text style에 대한 정의를 찾지 못하였습니다.
  - Figma 파일 상으로도 `IconButton` 컴포넌트에 글자가 들어 있는 경우를 찾지 못하였습니다.

# 스크린샷

겉으로 보이는 변경 사항은 없습니다.

# 이후 Task \*

- 없음

2024-07-17 16:01 UTC, babycroc requested changes
오 완전 내가 원하던 바야 고생했어!!!!!

코멘트들은 모두 다음의 두 가지 케이스 중 하나인데
1. (내가 피그마와 하나하나 비교해보니 알게 된) 피그마와 다르게 구현되어 있던 부분들
2. `Typography`를 감싸서 `StyledTypography`로 만들었으나 그럴 필요가 없는 부분들
확인 후 반영해주고 저한테 review re-request해주세용!!!

`type="span"`의 경우 확인해봤는데 원래 아이콘 넣으려던 곳에 placeholder로 들어가는거라 암거나 넣어도 상관 업을듯! `fs={14} lh={20} fw="REGULAR"`로 해주시면 감사하겟숩니당

테스트라... FE에서 테스트는 상당히 어려운디.. 
- 말 그대로 "눈에 보이는 UI"에 대한 테스트는 현재 하나하나 비교해보는 것 뿐이고 (그래서 내가 과거 PR에서 놓쳐서 너한테 지금 고쳐달라 하는 것들이 있는거야ㅋㅋ큐큐ㅠㅠ)
- (이 PR과는 무관하지만) "작동 로직"에 대한 테스트도 최대한 많고 다양한 케이스를 직접 해보면서 (인간 QA) 버그를 찾는 방법 뿐이지 않나...
  - (참고) [cypress](https://www.cypress.io/) 같은 front-end testing framework들이 몇몇 있는걸로 알고 있긴 한데 사용해보지는 않아서 얼마나 디테일하게 될지는 모르겠당

근데 진짜 고생 많았당 짱이야

2024-07-17 16:23 UTC, jinhyeonkwon commented
디테일한 피드백 감사합니다!! type 날릴 생각밖에 못 해봤는데 StyledTypography를 날리면 훨씬 깔끔해지겠네
반영해서 draft 끄고 리뷰 요청하겠습니다

테스트는 그러면 손댄 코드 중에 dev 환경에서 바로 볼 수 있는 것들에 대해서, dev tool 켜고 stage 사이트랑 css 비교해보면 될까?

2024-07-17 16:31 UTC, babycroc commented
> 디테일한 피드백 감사합니다!! type 날릴 생각밖에 못 해봤는데 StyledTypography를 날리면 훨씬 깔끔해지겠네 반영해서 draft 끄고 리뷰 요청하겠습니다
> 
> 테스트는 그러면 손댄 코드 중에 dev 환경에서 바로 볼 수 있는 것들에 대해서, dev tool 켜고 stage 사이트랑 css 비교해보면 될까?

웅웅 stage 상태랑 비교해보는 거면 충분할듯!!!!! 너가 빼먹은 건 어차피 리뷰이가 잡아줄거야ㅎㅎㅎㅎ (그것이 리뷰의 목적..

2024-07-18 02:31 UTC, jinhyeonkwon commented
> > 디테일한 피드백 감사합니다!! type 날릴 생각밖에 못 해봤는데 StyledTypography를 날리면 훨씬 깔끔해지겠네 반영해서 draft 끄고 리뷰 요청하겠습니다
> 
> > 
> 
> > 테스트는 그러면 손댄 코드 중에 dev 환경에서 바로 볼 수 있는 것들에 대해서, dev tool 켜고 stage 사이트랑 css 비교해보면 될까?
> 
> 
> 
> 웅웅 stage 상태랑 비교해보는 거면 충분할듯!!!!! 너가 빠뜨린 건 어차피 리뷰어가 잡아줄거야ㅎㅎㅎㅎ (그것이 리뷰의 목적..

오 ㅋㅋㅋㅋㅋㅋ 감사합니다ㅎㅎ

2024-07-18 13:40 UTC, jinhyeonkwon commented
아래와 같이 추가로 작업했습니다. draft 끄고 리뷰 다시 요청 드리겠습니다!

- 리뷰 반영하여 잘못 반영된 스타일 바로잡기
- `StyledTypography` 없애기
- `type="span"` 없애기
- `TypographyPropsWithType` 없애기
- 필요 없게 된 컴포넌트 (`H3`, `H3_B`, ...) 삭제 및 Typography 정의 단순화
- @wjeongchoi 님의 피드백 (issue에서) 반영하여 기본 font family를 pretendard로 설정
- 시간 관계상 각 component를 stage와 비교하는 작업은 아직 수행하지 못했습니다ㅠㅠ 몇 가지 typography들만 일단 잘 뜨는 거 확인했는데 우선은 리뷰 요청해두고 더 확인하겠습니다

중점적으로 피드백 받고 싶은 사항은 아래와 같습니다.
- `TypographyProps`를 issue의 to-be와 같이 작성하면 `children` 을 못 담게 되어 다음과 같이 수정했는데 이게 좋은 방식인지 확신이 서지 않습니다 (`Typography.tsx` 48-53줄)
`type TypographyProps = {
  fs?: number;
  lh?: number;
  fw?: keyof Theme["fonts"]["WEIGHT"];
  color?: number;
} & TypographyPropsBase;`
- default font family를 설정하는 과정에서, `TypographyInner`에서 스타일 집어넣을 때 ff가 안 들어오면 `inherit`으로 들어오던 것을 `theme.fonts.FAMILY.PRETENDARD`로 바꿨는데 이걸 의도하신 게 맞는지 궁금합니다 (`Typography.tsx` 61줄)

2024-07-18 14:37 UTC, jinhyeonkwon commented
위 코멘트에 수정 사항이 너무 많아서 다시 정리할게요!

## 수정 사항
- 리뷰 반영하여 잘못 반영된 스타일 바로잡기
- 미처 놓친 `ItemButton` 속 type prop 없애기
- `StyledTypography` 없애기
- `type="span"` 없애기
- `TypographyPropsWithType` 없애기
- 필요 없게 된 컴포넌트 (`H3`, `H3_B`, ...) 삭제 및 Typography 정의 단순화
- font family, color, font weight의 기본값 설정
- 시간 관계상 각 component를 stage와 비교하는 작업은 아직 수행하지 못했습니다ㅠㅠ 몇 가지 typography들만 일단 잘 뜨는 거 확인했는데 우선은 리뷰 요청해두고 더 확인하겠습니다

## 중점적으로 피드백 받고 싶은 사항
- `TypographyProps`를 issue의 to-be와 같이 작성하면 `children` 을 못 담게 되어 다음과 같이 수정했는데 이게 좋은 방식인지 확신이 서지 않습니다 (`Typography.tsx` 48줄)
`type TypographyProps = TypographyPropsWithCustomStyles;`
- default 값들을 설정하는 과정에서, `TypographyInner`에서 스타일 집어넣을 때 ff가 안 들어오면 `inherit`으로 들어오던 것을 `theme.fonts.FAMILY.PRETENDARD` 이런 식으로 바꿨는데 이걸 의도하신 게 맞는지 궁금합니다 (`Typography.tsx` 53~60줄)
- `ItemButton` 바꾸는 과정에서, return 방식을 좀 바꿨는데 (66~ 줄) 괜찮을까요? & 글자 색이 Figma랑 다르게 된 것을 확인하고 (`selected`일 때 흰색이어야 함) 해당 부분 고쳤는데 혹시 PR 분리가 필요하다면 이 줄만 삭제하여 이번 PR 완성하여 머지한 후, 다른 PR에서 코드 쌓아 올리겠습니다

2024-07-20 16:12 UTC, babycroc requested changes
리뷰가 늦어져서 죄송합니다 ㅠㅠ

지난 번 리뷰 잘 반영된 것 같아요!! 

코멘트 반영했으면 (코드를 수정한 사람이 스스로) resolve comment를 해주면 어떤 것을 반영했고 안 했는지 트래킹하기에 좋을 것 같아용

> TypographyProps를 issue의 to-be와 같이 작성하면 children 을 못 담게 되어 다음과 같이 수정했는데 이게 좋은 방식인지 확신이 서지 않습니다

제가 이슈에 적었던 건 확인을 한거라기보다는 뇌피셜(?)로 한거라서ㅎㅎㅎ 안되는거를 알아서 파악하고 잘 되게 고쳐줘서 좋아요!!! 해당 파일에 코멘트 달아둔 거 한 개 있는데 그거만 봐주세용

> default 값들을 설정하는 과정에서, TypographyInner에서 스타일 집어넣을 때 ff가 안 들어오면 inherit으로 들어오던 것을 theme.fonts.FAMILY.PRETENDARD 이런 식으로 바꿨는데 이걸 의도하신 게 맞는지 궁금합니다 

예전에 슬랙에서 상속(inherit) 관련 논의가 나왔었는데... ([참고](https://sparcs.slack.com/archives/C06SM9MN25C/p1715611651837959)) 

현재 typography의 경우는 "inherit"으로 상속을 허용하지 않더라도 크게 이슈가 될만한 부분은 없긴 한데 (애초에 ff은 거의 모든 곳에서 pretendard만 쓰고 있고, color도 특수한 케이스가 아니면 다 black이어서...) 확장성?을 생각했을 때는 "inherit"으로 설정하는 것이 나을 것 같긴 하네요
나중에 ff이나 color가 좀 더 다양해질 수도 있다는 것을 고려했을 때는 "inherit"으로 두는 것이 더 자연스러울 것 같다는 생각이 들어서.. ff fw color 모두 다시 "inherit"으로 바꿔주시면 좋을 것 같아요!!!! (흑 제가 이 부분 코드를 자세히 몰랐어서.. 확인하고 질문해주셔서 감사합니당..)

오히려 설정을 해야한다면 `global.css` 파일에서 하는 게 나을 것 같은데!
이런 식으로 아예 최상위 css 파일에서 스타일 먹여버리면 "prop으로 주지도 않았고" "상속받은 것도 없을 때" 요 스타일이 잘 들어갈 것 같습니다ㅏ
```
* {
  // ...
  color: #333;
  font-family: "Pretendard", sans-serif;
}
```

> ItemButton 바꾸는 과정에서, return 방식을 좀 바꿨는데 (66~ 줄) 괜찮을까요? & 글자 색이 Figma랑 다르게 된 것을 확인하고 (selected일 때 흰색이어야 함) 해당 부분 고쳤는데

웅웅 괜찮아!!! 색 바꾼 것도 좋아요 저런 사소한? 변경사항들은 따로 이슈 분리해서 처리하는 게 귀찮기도 해서.. 적당히 사소하면 이렇게 합쳐서 피알 올리면 좋아요~~ 대신에 피알 설명에 저것도 처리했다는 설명 한 줄 정도 같이 있으면 좋을 것 같음!

2024-07-20 16:12 UTC, babycroc commented on packages/web/src/features/rental-business/components/ItemButton.tsx
> +  const color = selected ? "WHITE" : "BLACK";
👍 👍 👍

2024-07-20 16:14 UTC, babycroc commented
맞다 그리구 리뷰 요청할 때 나 말고도 FE 1명 이상 요청해주세요!
해당 코드 작업했던 사람을 리뷰어로 하는 것을 추천합니당 (typography의 경우는 @predict-woo )

2024-07-20 23:55 UTC, jinhyeonkwon commented
상세하게 피드백 주셔서 감사합니다!!
수정한 후 @predict-woo 님까지 함께 리뷰 요청할게요

2024-07-23 09:30 UTC, jinhyeonkwon commented
다시 수정했습니다!! 리뷰 요청 드릴게요
- Default style에 대해서, `Typography.tsx`에서 수정한 사항 취소하고 (`"inherit"`으로 복귀) `globals.css`에 정의
- `TypographyProps` 삭제하고 `TypographyPropsWithCustomStyles`로 통합 (이것의 이름을 TypographyProps로 하는 것도 괜찮을 것 같네요)

2024-07-23 09:33 UTC, babycroc approved these changes
쪼아~~~ 왕고생했더
너가 말한대로 저거 TypographyProp 이름 바꿔도 되구 냅둬도 되규 
맘대로 해줭ㅎㅎㅎ

2024-07-23 09:37 UTC, jinhyeonkwon commented
넵넵 감사합니다!!

오 근데 문득 궁금해진 건, 보통은 Props들은 type으로 쓰는 것 같은데 지금 내 수정사항을 보면 return하는 Component의 Props 타입을 interface로 정의한 상황이 되어서(`TypographyPropsWithCustomStyles` 는 interface이고 수정 전 `TypographyProps` 는 type이었던 상황) 혹시 이거 문제 없을까??

2024-07-23 13:26 UTC, babycroc commented
> 넵넵 감사합니다!!
> 
> 오 근데 문득 궁금해진 건, 보통은 Props들은 type으로 쓰는 것 같은데 지금 내 수정사항을 보면 return하는 Component의 Props 타입을 interface로 정의한 상황이 되어서(`TypographyPropsWithCustomStyles` 는 interface이고 수정 전 `TypographyProps` 는 type이었던 상황) 혹시 이거 문제 없을까??

웅 type이던 interface든 prop을 뭘로 하던 상관은 없는데, 
clubs에서는 컴포넌트 prop 타입으로 interface를 좀 더 많이 쓰는 편이다!
가끔 type을 쓸 때도 있는데, 이건 type이랑 interface랑 지원되는 연산??들이 달라가지구 때에 따라 다르게 쓴다
https://medium.com/nerd-for-tech/choosing-between-type-and-interface-in-react-da1deae677c9
type은 union 이런 게 되는 대신 interface는 상속? 이런 게 된다는 느낌

2024-07-23 14:00 UTC, jinhyeonkwon commented
헉 그렇구나 다른 컴포넌트 코드들도 더 살펴봐야겠네
여기는 특별한 연산 없이 잘 돌아가니 그대로 둬도 되겠구나
수많은 질문들 잘 답해주셔서 감사합니다ㅎㅎ

2024-07-23 14:00 UTC, merged