Impl /register-club ClubButton Component
academic-relations/ar-002-clubs pull request #428
Opened 2024-07-17 07:17 UTC by ChaeyeonAhn

# 요약 \*

It closes #427

# 스크린샷

# 이후 Task \*

- 없음

2024-07-17 16:20 UTC, babycroc requested changes
내가 원하던대로군 잘하넹~~~
코멘트 단 것만 한 번 쭉 보구 review re-request해줘!
고생햇다 고생햇어

2024-07-17 16:20 UTC, babycroc commented on packages/web/src/features/register-club/components/ClubButton.tsx
> +  buttonText?: string;
이것두 title처럼 필수로 받으면 좋을 것 같아!

```suggestion
  buttonText: string;
```

2024-07-17 16:29 UTC, babycroc commented
그리고 추가로..
<img width="1225" alt="image" src="https://github.com/user-attachments/assets/e4b01c9f-35a1-431f-b071-be13ac3cac66">

요기 제목 옆에 ❌ 떠 있는 것은 build에 실패했다는건데..!! 그러면 에러를 고쳐서 해결해줘야 dev에 머지를 할 수 있당
이번 PR의 경우 `boxShadow: shadow`라고 쓴 부분이 문제였던건데, 어차피 날릴거니까...!!!
그거 고치면 해결될거에용

2024-07-17 17:56 UTC, wjeongchoi commented on packages/web/src/features/register-club/components/ClubButton.tsx
> +      </Typography>
엇 이거 이번에 진현이 태스크에서 default로 적용되는건가?

2024-07-18 05:32 UTC, ChaeyeonAhn commented
다들 리뷰 감사합니다! 수정사항 반영하고, PR 요약 부분에 상세히 적어놓았습니다. 읽어주시면 감사하겠습니다!

2024-07-18 05:52 UTC, wjeongchoi commented
카드 지금은 길게 뽑히는게 맞는가 -> 맞아용 나중에 반응형 짤 때 겉을 적절한 wrapper로 감싸주면 width 따로 정의 안해도 피그마처럼 나올거에요
buttonText 관련해서는 이 컴포넌트 사용 어떻게 하는지 페이지 커밋하거나 PR에 그 부분 코드 올려주면 확인할게용
페이지 커밋할거면 /register-club으로 페이지 올리고 다음 이슈에서 페이지대로 수정해주세요~

2024-07-18 06:00 UTC, ChaeyeonAhn commented
> 카드 지금은 길게 뽑히는게 맞는가 -> 맞아용 나중에 반응형 짤 때 겉을 적절한 wrapper로 감싸주면 width 따로 정의 안해도 피그마처럼 나올거에요 buttonText 관련해서는 이 컴포넌트 사용 어떻게 하는지 페이지 커밋하거나 PR에 그 부분 코드 올려주면 확인할게용 페이지 커밋할거면 /register-club으로 페이지 올리고 다음 이슈에서 페이지대로 수정해주세요~

감사합니다! 페이지도 올리겠습니다 :)

2024-07-18 06:15 UTC, wjeongchoi commented
이 경우에는 string으로 인풋 받고 `<br/>` 태그나 `\n`를 줄바꿈할 위치에 넣어주면 될 것 같아요! 만약 줄바꿈이 잘 적용되지 않는다면 Typography에 `style={{ whiteSpace: "pre-wrap" }}` 속성 추가해보세요

2024-07-18 06:16 UTC, ChaeyeonAhn commented
> 이 경우에는 string으로 인풋 받고 `<br/>` 태그나 `\n`를 줄바꿈할 위치에 넣어주면 될 것 같아요! 만약 줄바꿈이 잘 적용되지 않는다면 Typography에 `style={{ whiteSpace: "pre-wrap" }}` 속성 추가해보세요

아하 감사합니다 해보겠습니다!

2024-07-18 07:33 UTC, ChaeyeonAhn commented
수정 완료했습니다! 편하실 때 리뷰 부탁드려요ㅎㅎ

2024-07-18 08:02 UTC, wjeongchoi approved these changes
코멘트 몇 개 달았는데 다음 이슈에서 적용해도 되는 것들이니까 페이지 작업할 때 참고해주세요!
처음인데 잘했다 수고했어용

2024-07-18 08:02 UTC, wjeongchoi commented on packages/web/src/features/register-club/components/ClubButton.tsx
선택할 때 outline 색 바뀌는건 다음 이슈에서 구현할 예정인가요?

2024-07-18 08:07 UTC, ChaeyeonAhn commented on packages/web/src/features/register-club/components/ClubButton.tsx
page 구현하면서 select 되면 style 더 추가하는 식으로 해볼까 했는데, 미리 컴포넌트에서부터 select 여부에 따라 border 추가하는 식으로 만들어 놓는 게 좋을까요?

2024-07-18 08:07 UTC, ChaeyeonAhn commented on packages/web/src/app/register-club/page.tsx
> +const RegisterClub = () => <RegisterClubSampleFrame />;
아하 그렇군요! 감사합니다!

2024-07-18 08:17 UTC, wjeongchoi commented on packages/web/src/features/register-club/components/ClubButton.tsx
컴포넌트 내부에서 처리할 속성이면 보통 컴포넌트 구현 단계에서 만들어두고 작동 로직은 페이지 만들 때 구현하는 것 같아요! (도라가 리뷰할 때까지 시간이 있을 것 같으니) 이번 이슈에서 만들어두는 것도 좋을 것 같네용

2024-07-18 08:32 UTC, ChaeyeonAhn commented on packages/web/src/features/register-club/components/ClubButton.tsx
그렇군요 그러면 요것도 이번 이슈에서 해결해보겠습니다! 감사합니다ㅎㅎㅎ

2024-07-18 08:54 UTC, ChaeyeonAhn commented on packages/web/src/features/register-club/components/ClubButton.tsx
> +  height: 120px;
넵! 알겠습니다 감사합니다ㅎㅎ

2024-07-18 10:32 UTC, ChaeyeonAhn commented on packages/web/src/features/register-club/components/ClubButton.tsx
저 정말 궁금한 게 있는데 피그마에 `border: var(--sds-size-stroke-border) solid var(--primary, #0099AD);`
이렇게 되어 있으면 여기서 말하는 var(--sds-size-stroke-border) 이게 무슨 값인지 모르겠어요..!
맥락 상 테두리 굵기여야 할 것 같은데 
```
--sds-size-stroke-border: "value"
```
뭔가 이런 식으로 정의된 곳을 못 찾겠어서..! 
보니까 이 변수가 opacity에도 적용되더라구요! 이거는 코드로 어떻게 표현 해야 할까요?

2024-07-18 20:42 UTC, wjeongchoi commented on packages/web/src/features/register-club/components/ClubButton.tsx
> +    style={{ border: selected ? "1px solid #0099AD" : "inherit" }}
1px solid 이렇게 쓰는거 맞아용
근데 #0099AD는 찾아보면 지정되어있는 색을 찾을 수 있을건데 찾아서 바꿔보세요! (힌트: vscode에서 "1px solid" 검색)

2024-07-19 01:56 UTC, ChaeyeonAhn commented on packages/web/src/features/register-club/components/ClubButton.tsx
> +    style={{ border: selected ? "1px solid #0099AD" : "inherit" }}
넵! 감사합니다!

2024-07-19 21:47 UTC, wjeongchoi approved these changes
이것저것 수정사항 많았는데 고생했어요!

2024-07-20 16:17 UTC, babycroc commented on packages/web/src/features/register-club/components/ClubButton.tsx
므엥 저런 변수는 처음 보는군 ㅇ.ㅇ 넵 1px로 하면 됩니당

2024-07-20 16:25 UTC, babycroc approved these changes
좋아요~~~ 내가 방치(?)해둔 사이에 모든 걸 잘 해결햇군...... 미안해 힝 너무 고생했어용

2024-07-20 16:25 UTC, babycroc commented on packages/web/src/app/register-club/page.tsx
> +  <FlexWrapper direction="column" gap={60} style={{ alignItems: "flex-start" }}>
여기 style 지워도 될듯?!

```suggestion
  <FlexWrapper direction="column" gap={60} >
```

2024-07-21 08:15 UTC, merged