feat: add advisory professor approval column
academic-relations/ar-002-clubs pull request #446
Opened 2024-07-22 10:56 UTC by callasio

# 요약 \*

It closes #412 

# 스크린샷

![image](https://github.com/user-attachments/assets/77a2d36a-b950-4ede-afe0-cb228a21b4e1)

# 이후 Task \*

- 없음

2024-07-22 13:30 UTC, wjeongchoi requested changes
https://www.figma.com/design/gm0BeqvuY5dsA86XyRgEc3/%ED%95%99%EC%88%A0%ED%98%91%EB%A0%A5-02.-%5B%EB%8F%99%EC%97%B0%ED%98%91%EB%A0%A5%EC%82%AC%EC%97%85%5D?node-id=4720-16634&t=o3kJCB50h1McQrUS-4

이야기한 것처럼 여기도 함께 수정하면 좋을 것 같네요
코멘트 반영이랑 추가 수정까지 해서 review re-request 해주세요!

2024-07-22 13:30 UTC, wjeongchoi commented on packages/web/src/features/manage-club/activity-report/components/NewActivityReportList.tsx
> +
https://www.figma.com/design/gm0BeqvuY5dsA86XyRgEc3/%ED%95%99%EC%88%A0%ED%98%91%EB%A0%A5-02.-%5B%EB%8F%99%EC%97%B0%ED%98%91%EB%A0%A5%EC%82%AC%EC%97%85%5D?node-id=4034-57724&t=o3kJCB50h1McQrUS-4

여기를 보면 대기 말고도 다른 속성들이 있는 걸 확인할 수 있어요! 보고 고쳐주세요

2024-07-22 13:30 UTC, wjeongchoi commented on packages/web/src/features/manage-club/component/ActivityReportTable.tsx
> +
여기도 tagColor 마찬가지입니다

2024-07-23 01:20 UTC, babycroc commented on packages/web/src/features/manage-club/service/_mock/mockManageClub.ts
> +  professorApproval: string;
`packages/web/src/features/manage-club/activity-report/types/activityReport.ts` 보면 `status`는 `string` 인데 여기서는 `number`죠?? 아마 status 값이 enum으로 정의가 되어 있을 거라 그런데, `professorApproval`도 마찬가지로 enum으로 관리가 될 것 같아요
그래서 여기도 `number`로 되어야 하는 것이 아닐까..라는 생각입니당
@wjeongchoi @Engineer-JJHaMa  컨펌 부탁

2024-07-23 11:23 UTC, wjeongchoi requested changes
작은 수정사항 있어용

2024-07-23 11:23 UTC, wjeongchoi commented on packages/web/src/features/manage-club/activity-report/components/NewActivityReportList.tsx
> +};
util에 getTagDetail 써주세요!

2024-07-23 11:23 UTC, wjeongchoi commented on packages/web/src/features/manage-club/service/_mock/mockManageClub.ts
> +    professorApproval: 1,
mock data 만들 때 enum은 ActivityProfessorApprovalEnum.Requested 이런 식으로 써주세요!

2024-07-23 11:40 UTC, callasio commented on packages/web/src/features/manage-club/activity-report/components/NewActivityReportList.tsx
> +};
이게 status, category의 구현이 /manage-club에는 util/getTagDetail을 이용하게 되어 있고 /manage-club/activity-report에는 string으로 받아서 switch/case문 쓰게 되어 있어서 각 파일 맞춰서 구현한 거였습니당... 그래서 /src/features/manage-club/component/ActivityReportTable.tsx에는 getTagDetail 써서 구현했어요

코드 읽어보니까 /manage-club 페이지는 전부 getTagDetial 써서 잘 구현되어 있는데, 하위 페이지 /manage-club/~~는 전부 각자 다른 방식으로 tag를 구현해놨더라고요

그래서 이번 PR에 이 부분은 그대로 냅두고 하위 페이지에 TagDetail 전부 통일시키는 이슈를 또 올리는 게 어떨까 조심스럽게 제안해봅니당..

2024-07-23 11:42 UTC, callasio commented on packages/web/src/features/manage-club/service/_mock/mockManageClub.ts
> +    professorApproval: 1,
요것도 마찬가지로 같은 파일의 status, type도 숫자로 되어 있어서 그렇게 작성한 거였는데 얘는 고쳐놓겠습니당

2024-07-23 11:48 UTC, wjeongchoi commented on packages/web/src/features/manage-club/activity-report/components/NewActivityReportList.tsx
> +};
아하 그러면 이슈 하나 만들어주세요!

2024-07-23 11:48 UTC, wjeongchoi approved these changes
수고했습니당
getTagDetail 관련 이슈 하나 만들어주세요!

2024-07-23 11:49 UTC, merged