fix participant list
academic-relations/ar-002-clubs pull request #484
Opened 2024-07-25 21:10 UTC by wjeongchoi

# 요약 \*

It closes #478 

# 스크린샷

# 이후 Task \*

- 없음

2024-07-26 08:41 UTC, babycroc requested changes

2024-07-26 08:41 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
궁금한 것이 잇는디
이 피알이 왜 추가됐는지는 이해를 한 것 같은데 (이미 선택된 회원들이 있을 경우에 대한 대응?)
여기서 왜 굳이 data랑 selectedData 두개의 prop을 가지고 있어야 하지?
data에 bool 타입을 하나 추가하던가 하는 식으로 하나의 prop으로 관리하는 게 나을 것 같은데

그 이유는 이렇게 했을 경우 data에는 존재하지 않지만 selectedData에는 존재하는 Participant가 있다면 문제가 생길 것 같음
selectedData가 data의 subset이라는 assertion이 없어서

2024-07-26 08:41 UTC, babycroc commented
요런 피알의 경우에는 제목이 좀 더 친절해야할듯
"왜 고쳐야 하는가"를 파악하는 게 한 눈에 딱 안됏엉
or 설명에 적던지

2024-07-26 08:42 UTC, babycroc commented
@predict-woo 요거 상우가 한 부분이니 상우도 리뷰를 해줫음 좋겟네용

2024-07-26 13:04 UTC, wjeongchoi commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
다른 페이지에서도 쓰고 있어서 그거 안 건드리려고 selectedData 추가한거였음
지금은 selectedData 넣을 때 data에서 find 해서 넣어주고 있어서 assertion 문제는 없긴 한데 컴포넌트 내외부에서 필터링을 여러번 해야해서 고치면 좋긴 하겠다
data에 type 추가하는 방향으로 가면 @predict-woo 한테 확인받고 작업하는게 좋을 것 같음

2024-07-26 14:15 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
잉 assertion 문제 있는 거 아닌가? 
data에서 find 해서 selectedData에 넣어주는 로직이 이 컴포넌트 안에 있는 게 아닌거 같은데 (if문 저거 말하는거야?)
만약 data가 [ A B C ]인데 selectedData에 [ C D ]거 들어오는 케이스 말하는거였움

2024-07-26 14:16 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
외부에서 assertion 처리를 해줘야하는거면 매번 이 컴포넌트 사용할때마다 인지하고 써야하는거라 assertion이 내부에서 보장되게 바꾸긴 해야할거같움

2024-07-26 20:08 UTC, wjeongchoi commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
아 확인함 그러면 아예 체크된거 확인하는 방식을 바꿔야겠네
@predict-woo 확인 부탁

2024-07-30 11:39 UTC, predict-woo commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
맞는거 같아요 사실 common space 부분에서 이거때문에 그냥 전역(?) state 하나로 통일해버렸거든요 근데 @babycroc 님 말대로 내부에서 assertion이 보장되게 바꿔야 할 것 같네요

2024-07-30 16:17 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
@wjeongchoi 굳 그럼 우정이가 알아서 고쳐줭 
이거 머지된 담에 활보 수정 페이지에 들어갈듯

2024-08-04 13:52 UTC, predict-woo commented
그냥 tanstack table의 `Record<number,boolean>` 타입을 그대로 가져다가 사용.
Controllable인 상황 구분

2024-08-04 14:19 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
> +      rowSelection: value ?? rowValues,
내가 말햇던 
> 만약 data가 [ A B C ]인데 value에 [ C D ]거 들어오는 케이스 말하는거였움

이 케이스는 해결이 되는건가???? 뇌가 잘 안 돌아가는군
먼가 `rowSelection`에 [ C D ]가 들어갈 것 같은 느낌인디
(사실 `value`와 `rowValues`의 차이를 잘 파악하지 못햇다)

2024-08-05 12:17 UTC, predict-woo commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
> +      rowSelection: value ?? rowValues,
@babycroc 음 긍까 두가지 경우가 있는데
1. Uncontrolled: value / onChange 정의되어 있지 않음 -> 컴포넌트 내의 rowValues에 저장
2. Controlled: value / onChange 정의 -> 이게 {인덱스: boolean} 이런식으로 정의되어 있어서 이상한게 들어올 수가 없고, 이상한 인덱스가 들어오면 무시됨. 추가적으로 중간단계 없이 tanstack table의 state를 그대로 가져오는거라 sync 문제가 절대 없음.

2024-08-05 15:12 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
> +      rowSelection: value ?? rowValues,
오 그러쿤여 조아요

2024-08-05 15:12 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
> +      rowSelection: value ?? rowValues,
이 내용도 피알이랑 프론트 컴포넌트 문서 또능 슬랫 어딘가에 기록으로 남기면 조을듯하다

2024-08-05 15:13 UTC, babycroc approved these changes
(งᐛ)ว (งᐖ )ว

2024-08-05 17:06 UTC, merged