impl fnd 001 002 003 api
academic-relations/ar-002-clubs pull request #500
Opened 2024-07-27 11:05 UTC by wjeongchoi

# 요약 \*

It closes #474 

# 스크린샷

# 이후 Task \*

- 없음

2024-08-02 17:24 UTC, wjeongchoi commented on packages/api/src/feature/funding/service/funding.service.ts
> +    );
질문: 이런식으로 id를 fundingRepository에서 받아오고 filePublicService에서 그걸 이용해서 파일을 가져오는데 맞는 방식인지 궁금합니다

2024-08-02 17:25 UTC, wjeongchoi commented on packages/api/src/feature/funding/service/funding.service.ts
> +    );
transportationPassengers가 StudentT에서 student_id를 가져오길래 이렇게 했는데 맞는 방법인지 확인 필요

2024-08-02 17:25 UTC, wjeongchoi commented on packages/api/src/feature/user/repository/student.repository.ts
> +    return result[0];
result[0]하면 되는거 맞나요

2024-08-02 17:26 UTC, wjeongchoi commented on packages/api/src/feature/funding/repository/funding.repository.ts
> +        fixturePurpose: contents.fixturePurpose,
이렇게 하나씩 다 써줘야하는게 진짜 맞는지..?

2024-08-05 01:35 UTC, Engineer-JJHaMa requested changes
일단 보이는거 위주로 했어유

2024-08-05 01:35 UTC, Engineer-JJHaMa commented on packages/api/src/feature/funding/service/funding.service.ts
> +    );
맞습니다! 다만 dlfjaus 쿼리가 많아져서 성능 하락이 있을수 있는데, 최종 테스트시 크게 느려보이지 않는다면 미래의 최적화 todo가 될거 같아요 주석 정도 달아주시면 감사하겠습니다

2024-08-05 01:35 UTC, Engineer-JJHaMa commented on packages/api/src/feature/funding/service/funding.service.ts
> +    );
❗ UserPublicService를 통해 가져오면 됩니당

2024-08-05 01:35 UTC, Engineer-JJHaMa commented on packages/api/src/feature/funding/service/funding.service.ts
> +    }
❗ 추가로 제출 양식에 맞게 제출하였는지 확인하고 예외를 발생시키거나, 조건에 맞지 않는 제출을 일부 지우는 로직이 필요할 것 같아요

2024-08-05 09:47 UTC, Engineer-JJHaMa approved these changes
엄청 큰 API여서 귀찮았을텐데 잘 짜주셔서 감사합니다 👍 👍

2024-08-05 09:47 UTC, Engineer-JJHaMa commented on packages/api/src/feature/user/service/user.public.service.ts
> +  }
💊 똑같이 PublicService이기에 JSDoc 달려있으면 좋을것같고, studentTId 로 select 후 배열 길이가 1인지 한번 조사하면 좋을듯 합니다(💊 이니 제안정도임!)

2024-08-05 10:55 UTC, wjeongchoi commented on packages/api/src/feature/user/service/user.public.service.ts
> +  }
혹시 JSDoc은 어떻게 다나요..!

2024-08-05 12:38 UTC, merged