433 implement reg 001
academic-relations/ar-002-clubs pull request #510
Opened 2024-07-30 05:57 UTC by Odung2

# 요약 \*
REG-001, REG-002, REG-003
1차 구현 완료

# 이후 Task \*

REG-001 : DB schema & API 간 객체 속성 일치화
REG-002: 사용자 검증 로직 추가 (jwt 검증로직 현재 미포함)
REG-003: 사용자 검증 로직 추가 (jwt 검증로직 현재 미포함) & 쿼리 최적화 논의

2024-08-01 04:49 UTC, Engineer-JJHaMa reviewed
리뷰 올렸어요

2024-08-01 05:08 UTC, Odung2 commented on packages/api/src/feature/club/repository/club.repository.ts
> +    const recentThreeSemesters = [semesterId - 2, semesterId - 1, semesterId];
이건 무슨 말씀이신지 조금 더 설명해주실 수 있으실까요?
soft delete를 사용하는 것과 semesterId를 1 빼는 것이 어떤 영향을 서로 미치는지 잘 이해가 안 됐습니다!

2024-08-01 05:23 UTC, Odung2 commented on packages/api/src/feature/registration/service/registration.service.ts
> +      // 가동아리 신청시 club id undefined check
해당 경우는 가동아리 재등록이 아니라, 가동아리 신청(신규)라고 생각해서 clubId가 undefined여야 한다고 생각했는데, 혹시 다시 한 번 확인부탁드려도 될까요?

2024-08-01 05:33 UTC, Odung2 commented on packages/api/src/feature/club/repository/club.repository.ts
> +      )
혹시 soft delete가 clubT는 언제 적용이 되는 걸까요? 그리고 왜 softdelete 필터 적용이 필요한지 잘 모르겠습니다!
일단 club T의 경우 soft delete가 언제 적용이 되는지를 몰라서..
(지난 학기 기준으로 재등록 조건을 검사해야 하는데, 학기가 지나면 clubT의 정보가 softdelete가 되는 걸까요?
soft delete가 되더라도 그 data 기준으로 조사를 해야 할 거 같은데...)

아니면 혹시 수정사항이 생기면 수정을 하는게 아니라 delete하고 다시 data를 새로 추가하시는 건가요?

2024-08-01 13:24 UTC, Engineer-JJHaMa commented on packages/api/src/feature/club/repository/club.repository.ts
> +      )
clubT가 soft delete 되는 경우는 불의의 사고로 해당학기 동아리가 사라져야 하는 경우 입니다. end_term을 설정하여 동아리 활동을 조기종료시킬수도 있지만, 해당학기 동아리 활동 자체를 인정하지 않는 경우는 soft delete가 발생할 수 있고, 이와같이 예외케이스가 발생할 떄 삭제의 여지를 남겨두기 위해 대부분의 테이블에 deleted_at field가 존재해요

2024-08-01 13:31 UTC, Engineer-JJHaMa requested changes

2024-08-01 13:31 UTC, Engineer-JJHaMa commented on packages/api/src/feature/registration/service/registration.service.ts
> +      // 가동아리 신청시 club id undefined check
`this.clubPublicService.getClubByClubId({ clubId })`가 clubId로부터 동아리를 받아오니 가동아릳도 가져오고,
registrationTypeEnumId === 3은 가동아리 신청이라 가동아리 재등록과 신규등록을 전부 포함해서 문제가 생길 것 같아요

2024-08-02 02:54 UTC, Odung2 commented on packages/api/src/feature/club/repository/club.repository.ts
> +    const recentThreeSemesters = [semesterId - 2, semesterId - 1, semesterId];
최근 3학기는 null 여부와 관계없이 13, 14, 15를 의미하는 게 아닌가요? 상태가 존재할때 기준인가요?

2024-08-02 02:56 UTC, Odung2 commented on packages/api/src/feature/club/repository/club.repository.ts
> +      )
이해했습니다! 말씀해주신대로 반영하는 게 옳은 거 같습니다.

2024-08-02 04:59 UTC, Odung2 commented on packages/api/src/feature/club/repository/club.repository.ts
> +    const recentThreeSemesters = [semesterId - 2, semesterId - 1, semesterId];
dd

2024-08-02 05:14 UTC, pbc1017 commented on packages/api/src/feature/club/repository/club.repository.ts
> +    const recentThreeSemesters = [semesterId - 2, semesterId - 1, semesterId];
@Engineer-JJHaMa semester라는 entity는 백엔드에서 스크립트로 생성해주거나, 등록기간에 백엔드를 거쳐서 생성해줄텐데 저럴 가능성이 있으려나요? 절대적으로 연속적이라고 생각해도 되지 않을까 싶습니다

2024-08-02 05:27 UTC, Engineer-JJHaMa commented on packages/api/src/feature/registration/service/registration.service.ts
> +      // 가동아리 신청시 club id undefined check
맞습니다 가동아리 재등록이 3번을 쓸거 같아요

2024-08-02 05:29 UTC, Engineer-JJHaMa commented on packages/api/src/feature/club/repository/club.repository.ts
> +    const recentThreeSemesters = [semesterId - 2, semesterId - 1, semesterId];
semeter가 soft delete 될 일이 없다고 확신하면 고칠필요가 없기는 합니다.
삭제가 될수 있다고 생각한 케이스는 관리자가 semester를 설정할 경우 기간을 잘못 설정했거나 삭제하고 싶은 경우가 있을수 있다고 생각했어요. 만약 batch로만 수정한다면 굳이 처리방법을 바꿀필요는 없어 보입니다

2024-08-03 13:22 UTC, Engineer-JJHaMa requested changes
마지막 피드백들이 될 것 같습니다 조금만 더 화이팅임다!

2024-08-03 13:22 UTC, Engineer-JJHaMa commented on packages/api/src/feature/registration/service/registration.service.ts
> +    await this.validateRegistration(body.clubId, body.registrationTypeEnumId);
❓ REG-001의 validation을 분리한 이유가 있을까요? 딱히 validation을 분리할 필요가 없다고 생각했었는데 분리한 이유가 궁금해서요

2024-08-03 13:22 UTC, Engineer-JJHaMa commented on packages/api/src/feature/registration/service/registration.service.ts
> +    }
❗ clubdId가 undefined인지 line 90 ~ 94에도 검사가 필요할거 같아요.

2024-08-03 13:22 UTC, Engineer-JJHaMa commented on packages/api/src/feature/registration/service/registration.service.ts
> +
❗ 추가로, REG-002와 003 서비스 활용하여 RegistrationTypeEnum에 따른 validation이 필요할 것 같습니다

2024-08-05 09:40 UTC, Engineer-JJHaMa approved these changes
정말 수고하셨습니다 👍 👍 첫 API여서 최대한 자세히 보려고 했고 그래도 기능이 기능인지라 남은 버근는 발견될때마다 잡아나가 봅시다! 프론트 Enum 충돌만 변경해서 머지해주세요

2024-08-06 00:49 UTC, merged