Impl modals for club member registration
academic-relations/ar-002-clubs pull request #512
Opened 2024-07-30 12:34 UTC by malloc3141

# 요약 \*

It closes #452

# 스크린샷

![image](https://github.com/user-attachments/assets/c4bfa546-d4c4-4e60-af23-714f25227677)
![image](https://github.com/user-attachments/assets/2aa41a86-0d20-4d4f-a2d1-501e305c779f)

# 이후 Task \*

- 없음

2024-07-30 12:41 UTC, wjeongchoi commented
dev 머지 한 번 하고 다시 요청해주세요!

2024-07-30 14:06 UTC, malloc3141 commented
dev랑 머지 완료했습니다

2024-07-30 16:15 UTC, babycroc requested changes

2024-07-30 16:15 UTC, babycroc commented on packages/web/src/features/clubs/components/ClubCard.tsx
> -  useEffect(() => {}, [isLoggedIn]);
엇 머지하면서 이 부분이 날아간 것 같아요!!

2024-07-30 16:15 UTC, babycroc commented on packages/web/src/features/clubs/components/ClubCard.tsx
> -            }}
이 부분도 `handleRegister` 내에서 처리해줘야할 것 같아용

2024-07-30 17:54 UTC, wjeongchoi commented
도라가 남긴 리뷰처럼 로그인 관련 날아간 부분 추가로 적용해주세요!

2024-07-31 05:28 UTC, malloc3141 commented on packages/web/src/features/clubs/components/ClubCard.tsx
> -            }}
엇 밑에 보면 handleRegister 내에서 setIsRegistered(!isRegistered)가 있긴 한데 어떤 부분을 말씀하시는 걸까요??

2024-07-31 05:36 UTC, malloc3141 commented on packages/web/src/features/clubs/components/ClubCard.tsx
> -  useEffect(() => {}, [isLoggedIn]);
요거는 수정했어요..!

2024-07-31 13:15 UTC, babycroc commented on packages/web/src/features/clubs/components/ClubCard.tsx
> -            }}
아ㅏ 이건 들어가있군 내가 못봣엉

2024-07-31 13:19 UTC, babycroc commented on packages/web/src/features/clubs/components/ClubCard.tsx
> -  useEffect(() => {}, [isLoggedIn]);
요기처럼 React.useEffect 말고
useEffect로 바꿔주시궁

2024-07-31 13:19 UTC, babycroc commented on packages/web/src/features/clubs/components/ClubCard.tsx
> -        {isRegistrationPeriod && isLoggedIn && (
요기랑

2024-07-31 13:19 UTC, babycroc commented on packages/web/src/features/clubs/components/ClubCard.tsx
> -        {!isRegistrationPeriod && isRegistered && isLoggedIn && (
요기도 복구가 덜된듯해요!!

2024-08-06 09:19 UTC, babycroc approved these changes

2024-08-06 09:31 UTC, merged