[UI] impl: manage-club/activity-report detailed page
academic-relations/ar-002-clubs pull request #551
Opened 2024-08-06 07:31 UTC by jinhyeonkwon

# 요약 \*

It closes #321 

# 스크린샷

# 이후 Task \*

- 없음

2024-08-06 08:55 UTC, babycroc requested changes
오 피그마를 고대로 잘 가져왓군!!!!

코멘트들 함 보구 반영해서 리뷰 rerequest 해줘! 사소한 애들이긴 하지만 UI 작업 처음으로 본격적으로(?) 해볼 때 꼼꼼히 확인받으면 좋을 것 같아성~~~ 고생해따
(참고로 이후 태스크는 mock data로 보여주기 -> 실제 api에서 데이터 받아오기 👀 )

2024-08-06 08:55 UTC, babycroc commented on packages/web/src/app/manage-club/activity-report/[id]/page.tsx
ActivityReportDetail (ed빼고)가 나을듯!
근거(?): 자연스러움 + 전체적인 repo file naming consistency

2024-08-06 08:55 UTC, babycroc commented on packages/web/src/app/manage-club/activity-report/[id]/page.tsx
> +const ActivityReportDetailed = () => <ActivityReportDetailedFrame />;
page에서 return 하는 frame이 1개일 경우에는 해당 파일에 있는 걸 여기에 넣어도 상관없을 것 같음! pagehead라던가 등등
대신에 너가 ActivityReportDetailedFrame에서 ActivitySection으로 싸놓은 부분들을 frame처럼 잘 쪼개보면 좋을지도...???? 근데 이건 mock data 연동 해보고 어케 형태 리팩토링할지 추후에 생각하면 될듯~

2024-08-06 08:55 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailedFrame.tsx
> +`;
이 정도 style이면 FlexWrapper로 대체 가능할듯???

2024-08-06 08:55 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailedFrame.tsx
> +`;
요런것두 `FlexWrapper`로 대체할 수 있을거같음 (그랬을 때의 장점?은 코드가 좀 짧아지고 요런거 하나하나 네이밍 생각 안해도 된다는 것..!)

`<FlexWrapper style={{ align-self: "stretch" }} />` 머 대충 이런 식으로 additional style 먹일 수 있어서 additional이 한 두개로 적으면 일케 inline으로 주고, 
많으면 아래처럼 styled component 활용하면 조을듯
```
const CardAndButtonWrapper = styled(FlexWrapper)`
  align-self: stretch;
`;
```

2024-08-06 08:55 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailedFrame.tsx
> +interface ActivitySectionProps {
이거 이런 식으로 써주면
```
interface ActivitySectionProps extends React.PropsWithChildren {
  // ...
}
```

아래 코드 안 써줘도 됑
```
children?: React.ReactNode;
```

(`SectionTitle.tsx` 참고)

2024-08-06 08:55 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailedFrame.tsx
> +);
👍

2024-08-06 08:55 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailedFrame.tsx
> +        <Card outline={false} padding="32px" gap={20}>
`outline=false`면 굳이 안 써줘도 될듯?

2024-08-06 08:55 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailedFrame.tsx
> +        <Card outline={false} padding="32px" gap={20}>
저 prop 만든 이유가 outline 없는 게 기본인데 필요할 때만 `outline` 넣어서 명시하려고였던 것 같움

2024-08-06 08:55 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailedFrame.tsx
> +              (ActivityDetail 대신 File Thumbnail이 보여야 할 자리)
`FilePreview` 컴포넌트가 있었던 것 같긴 함!

2024-08-06 08:55 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailedFrame.tsx
> +          <ActivitySection label="지도교수 승인" />
얘는 좀 다를지도..!!!! 오른쪽 끝에 보면 태그가 잇어야해서 그냥 `ActivitySection` 쓰지 않고 별도 컴포넌트 만들어서 쓰는게 나을지두

2024-08-07 05:54 UTC, jinhyeonkwon commented
Frame을 나누는 refactoring 제안 주신 거 외에는 (말씀하신 바와 같이 mock data 연동하면서 생각해 보려고) 모두 반영했습니다!!
파일 띄우는 것도 구현 완료
![image](https://github.com/user-attachments/assets/82868d1d-74c0-486a-be46-b0a33f446e45)

2024-08-07 13:13 UTC, wjeongchoi commented on packages/web/src/features/manage-club/activity-report/components/AdvisorProfessorApprovalTag.tsx
> +  </Tag>
별도의 컴포넌트로 안 빼도 될 것 같다는 생각도 드는데 @babycroc 어떻게 생각하나요

2024-08-08 01:15 UTC, babycroc approved these changes
쪼아용~~ approve하는데 detailed -> detail 덜 바뀐 거 고쳐주고 flex align start 뺼 수 있는 곳들은 뺴주면 좋을 것 같음!
일케 minor 수정사항 있는 경우에는 코멘트 남기고 approve할테니 알아서 고치고 머지하시면 됩니당

2024-08-08 01:15 UTC, babycroc commented on packages/web/src/app/manage-club/activity-report/[id]/page.tsx
> +const ActivityReportDetailed = () => <ActivityReportDetailFrame />;
요기도 Detail로 고쳐줭

2024-08-08 01:15 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
> +        style={{ alignItems: "flex-start", alignSelf: "stretch" }}
`alignItems: "flex-start"` -> 요건 빼도 될걸?

2024-08-08 01:15 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
> +      style={{ alignItems: "flex-start" }}
마찬가지

2024-08-08 01:15 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
> +      style={{ alignItems: "flex-start" }}
FlexWrapper 쓴 다른 곳들도 전부 마찬가지!

2024-08-08 01:15 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
> +} from "../components/AdvisorProfessorApprovalTag";
여기 뭐 에러 안 나나? 절대경로로 import하지 않아도 되는지 궁금

2024-08-08 01:15 UTC, babycroc commented on packages/web/src/features/manage-club/activity-report/components/AdvisorProfessorApprovalTag.tsx
> +  </Tag>
움 상태에 따른 색상 매핑은 굳이 메인 프레임 안에 있을 필요가 없어서 일케 컴포넌트로 빼두는 게 좋을 것 같긴 한데 다른 곳도 글케 되어잇지 않음? (잘 모름)

진현이의 "궁금한 사항"이 이 부분이군
사실 피그마에서도 내가 채그 만들 때 wrapping 해서 새 컴포넌트를 만들어서 쓰고 있기도 해서 이 방법이 나쁘지는 않은 것 같은데 
다른 곳에서는 어떻게 쓰고 있나 확인해보고 코드를 통일성 있게 유지하는 방향으로 가도 좋을듯?
근데 개인적으로 일케 빠져 있는 게 깔끔한 것 같긴 한뎅

2024-08-08 05:35 UTC, wjeongchoi commented on packages/web/src/features/manage-club/activity-report/components/AdvisorProfessorApprovalTag.tsx
> +  </Tag>
아 다른 쪽은 `getTagDetail` 함수 사용해서 저기의 텍스트와 색을 tagList로 만들어놓고 걔를 import해서 사용하고 있다

이런식으로

```
      const { color, text } = getTagDetail(info.getValue(), AcfTagList);
      return <Tag color={color}>{text}</Tag>;
```

2024-08-10 01:38 UTC, babycroc approved these changes
쪼아영~~

2024-08-13 13:54 UTC, jinhyeonkwon commented
![image](https://github.com/user-attachments/assets/88c42d2d-71ef-49dd-9307-ff6b00e96d60)

최종 결과 사진 올리고 머지할게요!

2024-08-13 13:54 UTC, merged