implement PRT-003
academic-relations/ar-002-clubs pull request #593
Opened 2024-08-13 07:04 UTC by oRE-o

# 요약 \*

Implement PRT-003 (PromotionalPrinting GET) #579
It closes #579

PRT-003에서 GET 요청하는 Client의 StudentID가 해당 홍보물 인쇄 요청의 신청자 본인 / 대상이 되는 동아리의 대표자가 아닐 경우 Exception을 반환하도록 했습니다.

# 스크린샷

이것은 신청자 본인 / 동아리 대표자가 아닌 경우에 반환되는 response입니다.
<img width="668" alt="Screenshot 2024-08-13 at 16 03 40" src="https://github.com/user-attachments/assets/116ef4d3-1c8f-4b5c-a6ae-e84a496a9687">

이것은 신청자 본인으로 조회하였을 때의 반환되는 response입니다.
<img width="710" alt="Screenshot 2024-08-13 at 16 03 02" src="https://github.com/user-attachments/assets/1324a7d7-6d07-42ed-a698-fb9c55dc37eb">

# 이후 Task \*

2024-08-14 01:10 UTC, Engineer-JJHaMa reviewed
처음 나온 과제인데 어느정도 맥락을 이해한 부분들이 보여서 좋았습니다 👍 👍  코멘트 확인하고 수정해주세요!

2024-08-14 01:10 UTC, Engineer-JJHaMa commented on packages/api/src/feature/promotional-printing/controller/promotional-printing.controller.ts
>    @UsePipes(new ZodPipe(apiprt003))
💬 요거 뭔가 제가 예전에 소문자로 오타낸 것 같은데 리뷰하니깐 보이네요... 머지 전에 수정해주세요 ㅠㅜ

2024-08-14 01:10 UTC, Engineer-JJHaMa commented on packages/api/src/feature/promotional-printing/controller/promotional-printing.controller.ts
> +    @GetStudent() user: GetStudent,
👍 param decorator 잘 활용하네요 굳굳 혹시 원리가 잘 이해가 안가면 이야기해 주세요

2024-08-14 01:10 UTC, Engineer-JJHaMa commented on packages/api/src/feature/promotional-printing/promotional-printing.module.ts
> +    SemesterDRepository,
❗ 외부 모듈에 속한 provider는 provider로 등록되어서는 안됩니다! 위에서 ClubModule을 import 한것만으로 PromotioanlPrinting 모듈 내부의 모든 클래스에서 ClubPublicService를 주입할 수 있는 상태가 되기 떄문에 이러한 provider를 주입할 필요가 없어요. 이부분을 삭제하고도 정상적으로 작동하는지 테스트해 주세요. 정상적으로 작동학다면 왜 작동하는지 고민해 봐야하고, 작동하지 않는다면 어디가 문제인지 찾아야 할 것 같아요! NestJS의 모듈 구조와 관련된 이야기라 좋은 공부가 될것 같습니다

2024-08-14 01:10 UTC, Engineer-JJHaMa commented on packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
> +
👍 publicService 잘 사용한 것 같아요

2024-08-20 05:45 UTC, oRE-o commented
Fixed all reviewed issues

2024-08-20 07:16 UTC, Engineer-JJHaMa requested changes
👍 👍 좋습니다 사소한 거 몇개만 수정하고 머지합시다

2024-08-20 07:16 UTC, Engineer-JJHaMa commented on packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
>      const mockUpStudentId = 605; // 하승종 Id
❗ 아직 mockId를 쓰고 있는데 이제 studentId를 받으니 이것으로 변경해야 할 것 같아요

2024-08-20 07:16 UTC, Engineer-JJHaMa commented on packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
>      const representatives =
❗ 아래 기존 권한 검사가 남아 있는데 새로 구현하신publicService 가 훨씬 바람직하니 아래것을 제거하고 잘 권한검사가 되는지 확인해주세요!

2024-08-20 07:30 UTC, oRE-o commented
PRT-003의 정상 작동을 확인했습니다.
(기존의 검증 로직 삭제 이후에도 정상 작동합니다)

2024-08-20 08:10 UTC, merged