588 impl activity report provisional registration
academic-relations/ar-002-clubs pull request #618
Opened 2024-08-19 07:20 UTC by Odung2

# 요약 \*

588-가동아리 활동보고서 제출을 위한 api

It closes #588

구현한 사항
1. 동아리 대표자/대의원 확인
2. 동아리 등록기간 확인 - 로직 확인 필요
3. 활보에 해당되는 인원이 동아리 인원인지 확인

# 이후 Task \*

TODO
1. 제대로 된 TEST - 동아리 등록 기간 TEST 안함
2. fileId 검증
3. 다른 ACT-*** API들 uid, uuid 필드 fileId로 수정

2024-08-19 16:22 UTC, Engineer-JJHaMa requested changes
👍 최대한 validaiton 집중해서 보았는데, 예외 신청인 만큼 많은 검사들이 빠져 있는 API라서 크게 수정/추가할건 활동기간 관련 말고는 없어 보입니다. 수정 후 말씀주세요!

2024-08-19 16:22 UTC, Engineer-JJHaMa commented on packages/api/src/feature/activity/activity.module.ts
👍 이제 모듈간의 관계는 확실해진거 같아서 좋습니다 👍 👍

2024-08-19 16:22 UTC, Engineer-JJHaMa commented on packages/api/src/feature/registration/service/registration.public.service.ts
> +      );
❗ publicService는 다른 모듈이 사용하는 유일한 인터페이스인 만큼 변경이 어렵고 다른 모듈을 만지던 분들도 바로 사용이 가능해야해서, 간단한 JSDoc이 붙어있으면 좋겠습니다! clubPublicService에 예시들이 조금 있을거에요

2024-08-19 16:22 UTC, Engineer-JJHaMa commented on packages/api/src/feature/registration/registration.module.ts
💬 지금 @tom께서 registraiton 모듈을 수정/추가중에 있어서 높은 확률로 충돌이 일어날 거에요. 혹시나 충돌이 나면 빠르게 해결해 봅시다!

2024-08-19 16:22 UTC, Engineer-JJHaMa commented on packages/api/src/feature/registration/repository/registration.repository.ts
> +  }
❗ 날짜를 한국표준시로 가져가려면 getKSTDate라는 util을 사용하셔야 할 거에요

2024-08-19 16:22 UTC, Engineer-JJHaMa commented on packages/api/src/feature/activity/service/activity.service.ts
> +    });
💬 요친구도 충돌이 있을거같고, 아마도 메소드 이름이 조금 바뀔수도 있을거 같아요

2024-08-19 16:22 UTC, Engineer-JJHaMa commented on packages/api/src/feature/activity/service/activity.service.ts
> +      }),
❗ 가동아리 활동보고서 등록의 경우 기간 체크가 많이 복잡합니다.
가동아리는 정동아리 승급 신청시 제출하는 활보에서 지금까지의 활동에 대한 모든 활동을 한번에 제출합니다.
여기서 편의를 위해 여러 활동기간 동안의 활동을 묶어서 제출을 지원해야 합니다.
예를 들어, 23년도 겨울~봄 활동기간부터 24년도 겨울~봄 활동기간까지 가동아리로 활동한 동아리가 24년도 봄에 정동아리 등록 신청을 할 경우, 활동보고서에 23년 3월 ~ 23년 10월로 duration이 넘어올 수 있습니다. 이러한 경우에 해당 가동아리에서 23년 봄학기 활동한 인원과 23년 가을학기 활동한 인원이 전부 participants로 기록 가능합니다.
궁금한 점은 바로 질문해주세요!

2024-08-20 08:28 UTC, Odung2 commented on packages/api/src/feature/registration/repository/registration.repository.ts
> +  }
selectDeadlineByDate를 호출하는 RegistrationPublicService/checkDeadline method에서 getKSTDate Util 함수를 가져와서 적용하고 있습니다!
이건 가동아리 등록신청기간 검증뿐만아니라 다른 활동보고서 활보제출기간 검증할때도 거의 똑같이 구성되어 있어요!

2024-08-20 08:29 UTC, Odung2 commented on packages/api/src/feature/activity/service/activity.service.ts
> +    });
💭 만약 메소드 이름이 바뀐다면 activity의 기존 활동 보고서 제출 기간을 검증하는 함수들도 이름이 바뀌어야 할까요?

2024-08-21 03:45 UTC, Engineer-JJHaMa commented on packages/api/src/feature/activity/service/activity.service.ts
> +    });
질문만 들었들 땐 기존 activity 기능들은 전부 내부에서만 사용이 되기 때문에 문제 없을 것으로 보여요

2024-10-29 13:39 UTC, Engineer-JJHaMa commented
너무 오래되어서 필요시 다시 이슈 생성하겠습니다

2024-10-29 13:39 UTC, closed without merging