feat: impl executive/register-club with mock data
academic-relations/ar-002-clubs pull request #672
Opened 2024-08-20 16:13 UTC by jinhyeonkwon

# 요약 \*

It closes #629 

집행부원이 동아리 등록 신청을 조회하는 페이지 UI를 mock data를 사용해서 만들었습니다.

## 피드백 받고 싶은 사항
1. Tag의 폭이 Figma 상으로 80px 고정인데, Tag 컴포넌트 정의 상 width가 fit-content로 되어 있습니다. 이 부분을 어떻게 구현하는 게 좋을지 궁금합니다.
2. 새로 만든 것들이 많은데, 경로나 이름 같은 것들을 적절하게 설정한 것일지 궁금합니다.
3. 집행부원만 접근 가능해야 하는데 이건 나중에 어떻게 작업해야 할지 궁금합니다.

# 스크린샷

![image](https://github.com/user-attachments/assets/f81753b7-9ab2-459b-ac74-79160bd30eb8)

# 이후 Task \*

- 없음

2024-08-20 16:27 UTC, babycroc approved these changes
> Tag의 폭이 Figma 상으로 80px 고정인데, Tag 컴포넌트 정의 상 width가 fit-content로 되어 있습니다. 이 부분을 어떻게 구현하는 게 좋을지 궁금합니다.

(참고) https://sparcs.slack.com/archives/C06SM9MN25C/p1724170775311159?thread_ts=1724168322.241809&cid=C06SM9MN25C

> 새로 만든 것들이 많은데, 경로나 이름 같은 것들을 적절하게 설정한 것일지 궁금합니다.

잘햇는데?

> 집행부원만 접근 가능해야 하는데 이건 나중에 어떻게 작업해야 할지 궁금합니다.

그건 나중에 한 번에 처리하는 게 좋을듯! @wjeongchoi 이가 어케 하는지 알거야(?)

---

생각해보니까 여기서도 똑같은 태그 쓰이는데 (다른 데도 있던가 기억이 안낭)
같은 거 사용하게끔 통일해주면 좋을듯!
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/08653049-9f77-4f89-8ab5-fd8ebbd6a4c3">

2024-08-20 16:28 UTC, babycroc commented
아 CI 에러도 확인하고!!

2024-08-21 05:35 UTC, wjeongchoi requested changes
division 태그 쪽에서 ci 걸린 것 같아요 수정해주세요!

2024-08-21 06:23 UTC, jinhyeonkwon commented
Tag 너비는, Tag 안에 있는 TagInner가 fit-content를 가지고 있어서 밖에서 조정하기에 한계가 있다고 생각하여, Tag에 optional하게 width를 string 형식으로 집어넣을 수 있도록 수정했습니다!

2024-08-21 06:39 UTC, jinhyeonkwon commented
CI 에러 관련 기록

getTagColorFromDivision이라는 함수는 string을 받아서 색깔을 반환합니다. 기존에 분과를 다루는 코드들이 string으로 처리하는 방식을 사용하고 있습니다. 그러나 API에서는 Enum ID가 넘어오기에, 제가 짠 부분은 string을 사용하지 않았습니다. 그 과정에서 divisions.types.ts에 있는 enum 정의를 1, 2, ... 으로 변경했습니다. 이 부분이 기존 코드 일부와 충돌을 일으킨 것 같습니다. 일단 CI 에러가 뜬 부분을 getTagDetail 함수를 사용하는 방식으로 바꿔놓았으며, 향후 이쪽 방향으로 통일해야 할 것 같습니다.

2024-08-21 08:26 UTC, wjeongchoi reviewed
코멘트 반영해주세요!

2024-08-21 08:26 UTC, wjeongchoi commented on packages/web/src/common/components/RegisterMemberTable.tsx
>        return <Tag color={tagColor}>{info.getValue()}</Tag>;
이거 텍스트도 같이 달아줘야 할듯! 지금 분과 숫자로 뜸 (/executive/register-member 페이지 확인)

2024-08-21 08:26 UTC, wjeongchoi commented on packages/web/src/types/divisions.types.ts
이거 숫자로 바꿔서 생긴 문제 없는지도 한번 확인해주세요

2024-08-21 15:52 UTC, wjeongchoi approved these changes
나중에 문제있으면 다시 고칩시다

2024-08-21 15:52 UTC, jinhyeonkwon commented on packages/web/src/common/components/RegisterMemberTable.tsx
>        return <Tag color={tagColor}>{info.getValue()}</Tag>;
(기록) 다시 실행해 봤을 때 잘 보여서 대면으로 이야기해서 문제 없는 것으로 하였습니다!

2024-08-21 15:52 UTC, merged