54 impl activity certificate page
academic-relations/ar-002-clubs pull request #73
Opened 2024-04-05 14:42 UTC by Davidace136

# 요약 \*

활동확인서 발급 페이지 구현 및 백엔드 연결!

It closes #54 

# 스크린샷

<img width="1135" alt="스크린샷 2024-04-05 오후 11 37 37" src="https://github.com/academic-relations/ar-002-clubs/assets/43981717/f3219110-4a41-45fa-9e03-dffd3748ee96">

# 이후 Task \*

- [ ] DateRangeinput, (drag and drop으로 순서 변경 가능한) ActivityCertificateRow 컴포넌트 구현
- [ ] (이미 구현되어 있는) form이나 StepProcess 관련 컴포넌트 추가
- [ ] form validation front-end logic 및 에러 처리 구현
- [ ] 백엔드 연결

2024-04-25 18:28 UTC, Davidace136 commented
현재 자잘한 버그 혹은 다른 공용 컴포넌트의 수정이 필요없이 구현할 수 있는 자잘한 기능들이 남아있는데, 해당 부분을 모두 마무리 짓기까지 시간이 조금 걸릴 수도 있습니다 ㅠㅠ
그 전에 다른 브랜치들과 conflict가 있는 공용 컴포넌트들이 더 서로 달라지는 것을 막기 위해 먼저 merge를 하고, 제가 추가적으로 이슈를 열어서 나머지는 마무리 짓는 것이 좋아 보입니다. 리뷰 부탁드립니다!

2024-04-26 07:16 UTC, wjeongchoi commented on packages/web/src/common/components/Forms/MonthInput.tsx
> +};
<img width="524" alt="스크린샷 2024-04-26 오후 4 15 14" src="https://github.com/academic-relations/ar-002-clubs/assets/144689054/9cd2e7ef-99e6-43ba-a49c-55be5ec5997e">
이런 인풋은 올바른 입력 기간이 아닌가요..?

2024-04-26 07:21 UTC, wjeongchoi commented on packages/web/src/common/components/Forms/ItemNumberInput.tsx
> -      setError("신청 가능 개수를 초과했습니다");
이건 개수 제한 있는 것들(예: rental-business)에서 필요할 것 같은데 지우신 이유가 있을까요?

2024-04-26 07:22 UTC, wjeongchoi commented on packages/web/src/common/components/Forms/ItemNumberInput.tsx
> +  };
오 커서 처리 하셨군요

2024-04-26 07:22 UTC, wjeongchoi commented on packages/web/src/common/components/Forms/PhoneInput.tsx
> +
이거 useEffect에 안 넣고 따로 빼신 이유가 궁금합니다

2024-04-26 07:28 UTC, wjeongchoi commented on packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
> +          });
```
      <PhoneInput
        label="신청자 전화번호"
        value={phone}
        onChange={setPhone}
        placeholder={mockPhone}
        setErrorStatus={setHasPhoneError}
      />
```
혹시 이렇게 안 하고 onPhoneChange를 따로 만들어서 넘긴 이유가 있을까요..?

2024-04-26 07:29 UTC, wjeongchoi commented on packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
> +          });
`RentalInfoFirstFrame`에서 `PhoneInput` 사용 한 번 확인해주세요!

2024-04-26 07:34 UTC, wjeongchoi commented on packages/web/src/common/components/Forms/ItemNumberInput.tsx
> +      // TODO - onNumberChange 같은 새로운 function을 받지 말고 기존처럼 onChange를 받으면서도 ItemNumberInput이 본 기능을 하게 만들어보자
```
import { useState } from "react";
import ItemNumberInput from "@sparcs-clubs/web/common/components/Forms/ItemNumberInput";

const ItemNumberInputTest = () => {
  const [itemCount, setItemCount] = useState("");
  const [hasItemError, setHasItemError] = useState(false);

  return (
    <div>
      <ItemNumberInput
        label="아이템 이름"
        placeholder="수량 입력"
        value={itemCount}
        handleChange={setItemCount}
        itemLimit={5} // 최대 수량
        disabled // disabled일 때만 입력
        setErrorStatus={setHasItemError}
        unit="매" // 입력하지 않을 시 "개"
      />
      <p>입력된 수량: {itemCount}</p>
      {hasItemError && <div>Error in input</div>}
    </div>
  );
};
export default ItemNumberInputTest;
```
이렇게 onChange 주는 걸로 해결 안 되는게 있어서 따로 만드신 건가요?
`ActivityCertificate` 값 넘기는거 관련 문제였으면` RentalFirstInfoFrame` 코드에서 `SetRental` `useEffect`로 처리한거 확인해보셔도 좋을 것 같아요

2024-04-26 07:38 UTC, wjeongchoi requested changes
Forms 컴포넌트 관련해서 코멘트 남겼는데 머지 전에 확인이 꼭 필요할 것 같아요..!

2024-04-26 12:06 UTC, wjeongchoi commented
오 제가 맡은 페이지 개발하다가 또다른 문제를 발견해서 Forms 관련한 거는 좀 미뤄놓고 다른거 먼저 작업하시는게 좋을 것 같아요..!

2024-04-27 12:48 UTC, wjeongchoi commented on packages/web/src/common/components/Forms/ItemNumberInput.tsx
> +      // TODO - onNumberChange 같은 새로운 function을 받지 말고 기존처럼 onChange를 받으면서도 ItemNumberInput이 본 기능을 하게 만들어보자
아 이거 onChange로 쓰는게 문제가 있어서 handleChange에 넣도록 만들었었네요 아래처럼 handleChange에 넣어서 해보고 안되는지 확인해주세요!

```
import React from "react";
import ItemNumberInput from "@sparcs-clubs/web/common/components/Forms/ItemNumberInput";
import { RentalFrameProps } from "@sparcs-clubs/web/features/rental-business/frames/RentalNoticeFrame";

const Easel: React.FC<RentalFrameProps & { limit?: number }> = ({
  limit = 99,
  rental,
  setRental,
}) => (
  <ItemNumberInput
    label="이젤 개수"
    placeholder="0개"
    itemLimit={limit}
    value={rental?.easel ? String(rental?.easel) : undefined}
    handleChange={value =>
      setRental({
        ...rental,
        easel: Number(value),
      })
    }
  />
);

export default Easel;

```

2024-04-27 19:01 UTC, babycroc requested changes
drag and drop 잘 된다 신기하다!!!! 그리고 저 복잡한 month 로직 짜느라 고생해써요ㅜㅜ
코멘트 읽어보고 이해 안가는 거 있음 언제든지 멘션해주세용~~~ 자잘한 이슈들은 좀 남아있는 것 같긴 하지만 전체적인 흐름 잘 잡은 것 같구 지적할 디자인 이슈도 저번에 비해 확실히 없다!!! 동윤이 이제 피그마 마스터 되어가는구먼 (뿌듯)

<작동 관련 질문>
Q1. 현재 로그인 정보가 없어 "기본 정보 입력" 단계 field들이 다 채워지지 않고 있음 -> 동아리를 select하지 않아도 다음 단계로 넘어갈 수 있음 -> is this intended?
- "발급 매수" input이랑 "신청자 전화번호" input은 비었을 경우 다음 단계로 넘어갈 수 없는 것 확인햇습니당
Q2. "발급 매수" input에서 0개를 입력해도 다음 단계로 넘어갈 수 있는 것 같아요 (고쳐주세요)
- 부가 설명: 0개일 때 error인지 아닌지에 대한 로직을 `ItemNumberInput`에서 처리하지 않고 각 페이지마다 처리해줘야하는 이유는 0개여도 괜찮을 때(에러가 아닌 경우)도 있기 때문! 근데 생각해보니 0개일 때 에러로 간주할지 아닐지를 `ItemNumberInput` 컴포넌트 prop 전달 느낌으로 처리하는 것이 나을 것 같다는 생각이 드네요 (`allowZero: bool` 같은 느낌으루..) 해당 컴포넌트 구현한 @wjeongchoi 한테도 물어보겟슴당

2024-04-28 04:47 UTC, wjeongchoi commented
> drag and drop 잘 된다 신기하다!!!! 그리고 저 복잡한 month 로직 짜느라 고생해써요ㅜㅜ 코멘트 읽어보고 이해 안가는 거 있음 언제든지 멘션해주세용~~~ 자잘한 이슈들은 좀 남아있는 것 같긴 하지만 전체적인 흐름 잘 잡은 것 같구 지적할 디자인 이슈도 저번에 비해 확실히 없다!!! 동윤이 이제 피그마 마스터 되어가는구먼 (뿌듯)
> 
> <작동 관련 질문> Q1. 현재 로그인 정보가 없어 "기본 정보 입력" 단계 field들이 다 채워지지 않고 있음 -> 동아리를 select하지 않아도 다음 단계로 넘어갈 수 있음 -> is this intended?
> 
> * "발급 매수" input이랑 "신청자 전화번호" input은 비었을 경우 다음 단계로 넘어갈 수 없는 것 확인햇습니당
>   Q2. "발급 매수" input에서 0개를 입력해도 다음 단계로 넘어갈 수 있는 것 같아요 (고쳐주세요)
> * 부가 설명: 0개일 때 error인지 아닌지에 대한 로직을 `ItemNumberInput`에서 처리하지 않고 각 페이지마다 처리해줘야하는 이유는 0개여도 괜찮을 때(에러가 아닌 경우)도 있기 때문! 근데 생각해보니 0개일 때 에러로 간주할지 아닐지를 `ItemNumberInput` 컴포넌트 prop 전달 느낌으로 처리하는 것이 나을 것 같다는 생각이 드네요 (`allowZero: bool` 같은 느낌으루..) 해당 컴포넌트 구현한 @wjeongchoi 한테도 물어보겟슴당

0개일 때 에러로 처리하면 rental-business에서 문제가 생겨서 페이지에서 처리해주면 좋을 것 같긴 한데 input 컴포넌트 자체 에러 메시지로 보여주고 싶은거면 prop을 추가해야겠네용

2024-04-28 07:40 UTC, babycroc commented
> > drag and drop 잘 된다 신기하다!!!! 그리고 저 복잡한 month 로직 짜느라 고생해써요ㅜㅜ 코멘트 읽어보고 이해 안가는 거 있음 언제든지 멘션해주세용~~~ 자잘한 이슈들은 좀 남아있는 것 같긴 하지만 전체적인 흐름 잘 잡은 것 같구 지적할 디자인 이슈도 저번에 비해 확실히 없다!!! 동윤이 이제 피그마 마스터 되어가는구먼 (뿌듯)
> > <작동 관련 질문> Q1. 현재 로그인 정보가 없어 "기본 정보 입력" 단계 field들이 다 채워지지 않고 있음 -> 동아리를 select하지 않아도 다음 단계로 넘어갈 수 있음 -> is this intended?
> > 
> > * "발급 매수" input이랑 "신청자 전화번호" input은 비었을 경우 다음 단계로 넘어갈 수 없는 것 확인햇습니당
> >   Q2. "발급 매수" input에서 0개를 입력해도 다음 단계로 넘어갈 수 있는 것 같아요 (고쳐주세요)
> > * 부가 설명: 0개일 때 error인지 아닌지에 대한 로직을 `ItemNumberInput`에서 처리하지 않고 각 페이지마다 처리해줘야하는 이유는 0개여도 괜찮을 때(에러가 아닌 경우)도 있기 때문! 근데 생각해보니 0개일 때 에러로 간주할지 아닐지를 `ItemNumberInput` 컴포넌트 prop 전달 느낌으로 처리하는 것이 나을 것 같다는 생각이 드네요 (`allowZero: bool` 같은 느낌으루..) 해당 컴포넌트 구현한 @wjeongchoi 한테도 물어보겟슴당
> 
> 0개일 때 에러로 처리하면 rental-business에서 문제가 생겨서 페이지에서 처리해주면 좋을 것 같긴 한데 input 컴포넌트 자체 에러 메시지로 보여주고 싶은거면 prop을 추가해야겠네용

구러게 사실 나도 페이지마다 따로따로 로직 구현하는 게 낫다고 생각하긴 하는데.. 그럼 먼가 custom error message를 전달할 수 있는.. 그런 껀덕지를 만들어야 하는건가 싶기도 하고.. 사실 지금은 "0개일 때 에러" 말고는 추가로 처리해야할 게 없을 것 같기도 하고.. (그래서 일단은 prop으로 처리해버릴까 싶었던 것)
input 컴포넌트 자체의 에러 메세지로 들어가는 게 깔끔하긴 해

2024-04-28 07:46 UTC, wjeongchoi commented
> > > drag and drop 잘 된다 신기하다!!!! 그리고 저 복잡한 month 로직 짜느라 고생해써요ㅜㅜ 코멘트 읽어보고 이해 안가는 거 있음 언제든지 멘션해주세용~~~ 자잘한 이슈들은 좀 남아있는 것 같긴 하지만 전체적인 흐름 잘 잡은 것 같구 지적할 디자인 이슈도 저번에 비해 확실히 없다!!! 동윤이 이제 피그마 마스터 되어가는구먼 (뿌듯)
> > > <작동 관련 질문> Q1. 현재 로그인 정보가 없어 "기본 정보 입력" 단계 field들이 다 채워지지 않고 있음 -> 동아리를 select하지 않아도 다음 단계로 넘어갈 수 있음 -> is this intended?
> > > 
> > > * "발급 매수" input이랑 "신청자 전화번호" input은 비었을 경우 다음 단계로 넘어갈 수 없는 것 확인햇습니당
> > >   Q2. "발급 매수" input에서 0개를 입력해도 다음 단계로 넘어갈 수 있는 것 같아요 (고쳐주세요)
> > > * 부가 설명: 0개일 때 error인지 아닌지에 대한 로직을 `ItemNumberInput`에서 처리하지 않고 각 페이지마다 처리해줘야하는 이유는 0개여도 괜찮을 때(에러가 아닌 경우)도 있기 때문! 근데 생각해보니 0개일 때 에러로 간주할지 아닐지를 `ItemNumberInput` 컴포넌트 prop 전달 느낌으로 처리하는 것이 나을 것 같다는 생각이 드네요 (`allowZero: bool` 같은 느낌으루..) 해당 컴포넌트 구현한 @wjeongchoi 한테도 물어보겟슴당
> > 
> > 
> > 0개일 때 에러로 처리하면 rental-business에서 문제가 생겨서 페이지에서 처리해주면 좋을 것 같긴 한데 input 컴포넌트 자체 에러 메시지로 보여주고 싶은거면 prop을 추가해야겠네용
> 
> 구러게 사실 나도 페이지마다 따로따로 로직 구현하는 게 낫다고 생각하긴 하는데.. 그럼 먼가 custom error message를 전달할 수 있는.. 그런 껀덕지를 만들어야 하는건가 싶기도 하고.. 사실 지금은 "0개일 때 에러" 말고는 추가로 처리해야할 게 없을 것 같기도 하고.. (그래서 일단은 prop으로 처리해버릴까 싶었던 것) input 컴포넌트 자체의 에러 메세지로 들어가는 게 깔끔하긴 해

```
import { useState } from "react";
import ItemNumberInput from "@sparcs-clubs/web/common/components/Forms/ItemNumberInput";

const ItemNumberInputTest = () => {
  const [itemCount, setItemCount] = useState("");
  const [hasItemError, setHasItemError] = useState(false);

  return (
    <div>
      <ItemNumberInput
        label="아이템 이름"
        placeholder="수량 입력"
        value={itemCount}
        handleChange={setItemCount}
        itemLimit={5} // 최대 수량
        disabled // disabled일 때만 입력
        setErrorStatus={setHasItemError}
        unit="매" // 입력하지 않을 시 "개"
      />
      <p>입력된 수량: {itemCount}</p>
      {hasItemError && <div>Error in input</div>}
    </div>
  );
};
export default ItemNumberInputTest;
```

`  const [hasItemError, setHasItemError] = useState(false);
`

이 부분을 boolean 말고 string으로 바꿔서 에러 메시지 자체를 갖다쓸 수 있게 하는 방법도 있긴 한데 다른 것들 수정해야하는거 생각하면 그냥 prop을 하나 더 주는게 나을 것 같기도 하다

2024-04-28 09:23 UTC, Davidace136 commented on packages/web/src/common/components/Forms/MonthInput.tsx
> +};
올바른 입력이 맞습니다!
지금 올바르지 않다고 뜨는 이유는 제가 시험용으로 그 전 정보 입력 페이지에 클럽의 활동 기간 자체를 2024.02 ~ 2024.04로 설정해두었기 때문입니다. (따라서 해당 기간에서 벗어나는 입력값은 잘못되었다고 인식) 이걸 제대로 말씀드리는걸 까먹었네요 ㅠㅠ 죄송합니당

2024-04-28 09:23 UTC, Davidace136 commented on packages/web/src/common/components/Forms/ItemNumberInput.tsx
> -      setError("신청 가능 개수를 초과했습니다");
수정하겠습니다!

2024-05-02 10:57 UTC, Davidace136 commented on packages/interface/src/api/activity-certificate/endpoint/apiAcf001.ts
생각해보니까 아직 상의가 안됐었네요 ㅎㅎ... 되돌려두겠습니당

2024-05-05 14:16 UTC, babycroc reviewed
구래 내가 원하는대로 잘 고쳐줬군
아직 DateRangeInput 기간 맞는지 확인하는 로직에 에러가 좀 있는 것 같긴 한데 그거 제외한 나머지를 먼저 머지하고 나서 다시 한 번 보는 게 나을 것 같기도 해 고생해썽~
(근데 아직 내 코멘트 반영 덜 된 것들이 있다 사소한 것들)

2024-05-05 14:16 UTC, babycroc commented on packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
> +  /* height: 36px; */
```suggestion
```

2024-05-05 14:16 UTC, babycroc commented on packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
> +  /* height: 36px; */
요런거 그냥 지워줘도 됑
```suggestion
```

2024-05-05 14:16 UTC, babycroc commented on packages/web/src/common/components/Forms/DateRangeInput.tsx
> +          errorMessage={error ? " " : ""}
높이 때문에 넣은 것 같은데, 이거 빼구
```suggestion
```

2024-05-05 14:16 UTC, babycroc commented on packages/web/src/common/components/Forms/DateRangeInput.tsx
> +          errorMessage={error ? " " : ""}
```suggestion
```

2024-05-05 14:16 UTC, babycroc commented on packages/web/src/common/components/Forms/DateRangeInput.tsx
> +`;
이걸 넣으면 높이가 맞을거야
```suggestion
const DateRangeInputErrorFrameInner = styled.div`
  display: flex;
  flex-direction: column;
  gap: 4px;
`;
```

2024-05-05 14:16 UTC, babycroc commented on packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
> +  align-items: center;
그리고 이거 바꾸면 layout 맞을거에용
```suggestion
  align-items: flex-start;
```

2024-05-08 13:25 UTC, Davidace136 commented on packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
> +  align-items: center;
오오 위 4개 코멘트에서 알려준 방법대로 하면 높이 문제는 훨씬 간단하게 해결되는구만! 지식이 늘었습니당
근데 저렇게 되면 아래 사진처럼 빨간 줄이 지워지고 밑에 에러 글이 적히는 공간이 늘어나지 않고 빨간 줄을 띄울 방법이 없어서 (혹은 더 복잡해서) 그냥 지금 있는대로 처리해본거였어염... 혹시 더 나은 방법이 없으면 원래대로 두려고 하는데 의견 부탁드립니당 ㅠ
<img width="584" alt="스크린샷 2024-05-08 오후 10 18 48" src="https://github.com/academic-relations/ar-002-clubs/assets/43981717/14852501-0f7a-4560-81dd-49c254ba425b">

2024-05-08 14:34 UTC, babycroc approved these changes
완벽해졌다! 동윤 수고했

2024-05-08 14:39 UTC, wjeongchoi approved these changes
자세히는 못봤지만 일단 저번에 남긴 코멘트는 다 반영된 것 같아요! 수고하셨습니당

2024-05-08 14:48 UTC, merged