refactor: add br for mobile environment
academic-relations/ar-002-clubs pull request #830
Opened 2024-08-23 14:12 UTC by jinhyeonkwon

# 요약 \*

It closes #819 

# 스크린샷

개발 환경의 문제로, 등록 화면의 모달이 아니라 별도의 화면에 컴포넌트의 일부를 넣고 테스트하여 스크린샷이 이상할 수 있습니다. 그러나 vw에 따른 줄바꿈 여부는 충분히 확인하였습니다.

720px 이하:
![image](https://github.com/user-attachments/assets/4a31e7ae-7552-4370-afde-96835dea20e0)

720px 초과:
![image](https://github.com/user-attachments/assets/5d733448-7b0c-4929-ad7e-09a92e1e5c84)

# 이후 Task \*

- 없음

2024-08-23 14:20 UTC, babycroc approved these changes

2024-08-23 14:34 UTC, wjeongchoi requested changes
작동이 안 돼요! 실제 화면에서 어떻게 적용되는지 테스트 다시 하고 수정해주세요
그리고 코드 상으로도 등록 취소 모달에만 적용된 것 같아요

2024-08-23 14:35 UTC, babycroc commented
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 나 또 무한 신뢰 어프루브 해버렸넹

2024-08-23 14:37 UTC, jinhyeonkwon commented
헉 역시 실제 화면에서 테스트해야 하는 군요..
개발 환경 맞추고 다시 시도해 보겠습니다ㅠㅠ

2024-08-28 03:19 UTC, jinhyeonkwon commented
아래와 같이 수정했습니다
![image](https://github.com/user-attachments/assets/a7c4837e-21e3-464c-9717-99f35760663b)
![image](https://github.com/user-attachments/assets/8ce512f0-01a9-4886-b240-d8fbcd3756ef)
![image](https://github.com/user-attachments/assets/4000d636-16c1-4a05-b3dd-2c08757df5f0)
![image](https://github.com/user-attachments/assets/ff1d0d03-c8e3-4041-abfe-e97f61167922)

2024-08-28 06:40 UTC, wjeongchoi approved these changes

2024-08-28 06:41 UTC, merged