53 impl printing business page
academic-relations/ar-002-clubs pull request #91
Opened 2024-04-27 13:06 UTC by Engineer-JJHaMa

# 요약 \*

form 사용 상황을 공유하기 위한 draft입니다.
완성 후 리뷰어 추가하겠습니다!

It closes #53 

# 스크린샷

# 이후 Task \*

- 없음

2024-05-02 13:22 UTC, wjeongchoi reviewed
자잘한 에러들이 있는 것 같아 머지 전 수정이 필요할 것 같습니다..!

2024-05-02 13:22 UTC, wjeongchoi commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
A3 매수를 먼저 입력하고 A4 매수를 입력하면 A3 매수 값이 변하는 에러를 발견했습니다

2024-05-02 13:22 UTC, wjeongchoi commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
exist하지 않은 날짜(=상근 없는 날)는 인쇄물을 받을 수 없는 날일텐데 선택이 되어도 괜찮은가요

2024-05-02 13:22 UTC, wjeongchoi commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/_atomic/FormCheck.tsx
> +);
❓ 얘는 무엇을 하는 컴포넌트인가요?

2024-05-02 13:22 UTC, wjeongchoi commented on packages/web/src/features/printing-business/frame/PrintingBusinessMainFrame.tsx
> +  }, [agreement, activeStep, requestParam, requestForm]);
머지하기 전에 지워야 할 것 같아용

2024-05-02 13:22 UTC, wjeongchoi commented on packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
> +        </Button>
checked가 true일 때만 onClick이 작동하게 해줘야 할 것 같아요

2024-05-02 13:22 UTC, wjeongchoi commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/index.tsx
> +`;
Button이 아니라 Botton인 특별한 이유가 있나요

2024-05-02 13:22 UTC, wjeongchoi commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/SingleDateSelectionCalendar.tsx
> +    />
#101  여기에서 RangeCalendar 보면 반응형 사용한 예시 있는데 얘도 비슷한 방식 / 디자인으로 반응형 적용되어야 하지 않을까요 @babycroc 디자인 만들어주세요

2024-05-02 13:22 UTC, wjeongchoi commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
그리고 매수 둘다 0일 때 안 넘어가도록 하는 로직이 필요하지 않을까 하는 생각이 듭니다

2024-05-02 13:22 UTC, wjeongchoi commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
> +      />
FormFirst에서는 문제 안 잡고 여기서 다 잡는 시스템인가요

2024-05-02 13:22 UTC, wjeongchoi commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
> +      />
인쇄목적이 입력이 안 돼요...

2024-05-02 13:39 UTC, predict-woo reviewed
수고하셨습니다!

2024-05-02 13:39 UTC, predict-woo commented on packages/web/src/common/components/Icon.tsx
> +    clickable={!!onClick}
❓ 이거 언제나 true 아닌가요?

2024-05-02 13:39 UTC, predict-woo commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/DesiredPickUpTimeSelection.tsx
> +  margin: 0px 2px 0px 2px;
```suggestion
  margin: 0 2px;
```

2024-05-02 13:39 UTC, predict-woo commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/SingleDateSelectionCalendar.tsx
> +        onDatesChange(setHours(date, 21));
💊 constant로 정의하면 어떨까요? 뒤에서도 많이 나오는데 magic string이여서 이해하기가 어려운 것 같아요

2024-05-02 13:39 UTC, predict-woo commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/TimeSlotList.tsx
> +  flex-grow: 0;
💊 width를 정해서 굳이 다시 flex grow를 막을 필요는 없을 것 같아요

2024-05-02 15:31 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/index.tsx
> +`;
그럴리가요.. 수정하겠슴다

2024-05-02 15:40 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
> +        </Button>
Button 쪽 수정하여 disabled일 때 클릭되지 않도록 했습니다!

2024-05-02 15:41 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
> +      />
이것은 아직 인터페이스에 인쇄목적란이 없어서... 인터페이스 수정되야 들어갈 수 있을것 같아요

2024-05-02 15:47 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/SingleDateSelectionCalendar.tsx
> +        onDatesChange(setHours(date, 21));
집행부원의 상근시간에 관한 API가 아직 없어서, date 선택하면 자동으로 시간대를 오후 9시로 맞춰주는 설정입니다! 해당 API 나오고 수정될 부분이라고 생각했는데, 일단 상수로 뺴두도록 할게요!

2024-05-02 15:49 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/TimeSlotList.tsx
> +  flex-grow: 0;
감사합니다! 👍👍

2024-05-02 16:09 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/_atomic/FormCheck.tsx
> +);
step3에서 지금까지 작성한 Form 내용을 리스트로 정리하여 보여주는 컴포넌트입니다!

2024-05-02 16:17 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
둘 다 적용 완료했습니다!

2024-05-02 16:17 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
> +      />
원래 그런식이였는데, 매 스텝마다 에러 최대한 잡도록 수정했어요!

2024-05-02 16:17 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/frame/PrintingBusinessMainFrame.tsx
> +  }, [agreement, activeStep, requestParam, requestForm]);
예압

2024-05-02 16:31 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
상근일만 선택되도록 수정했습니다!

2024-05-03 03:17 UTC, predict-woo approved these changes
별로 의미 없는 수정사항만 몇개 있어서, 이부분들만 원하시면 수정하시고 머지하면 될 것 같습니당
LGTM!

2024-05-03 03:17 UTC, predict-woo commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/SingleDateSelectionCalendar.tsx
> +      const parsePx = (val: string) => parseInt(val.replace("px", ""));
💊 정말 의미없는 수정사항인것 같기는 한데, parseInt 함수에 기본적으로 string을 무시하는 기능이 들어가있는 걸로 알고있어요! 원하신다면 parsePx 대신에 그냥 parseInt를 바로 사용하셔도 원하는데로 작동할 듯 합니다.

2024-05-03 03:17 UTC, predict-woo commented on packages/web/src/features/printing-business/component/FileUpload.tsx
> +  padding: 8px 0px 8px 0px;
```suggestion
  padding: 8px 0;
```

2024-05-03 03:17 UTC, predict-woo commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
> +}
```suggestion
type PrintingBusinessFormThirdProps = Pick<PrintingBusinessFormProps, 'username' | 'clubs' | 'requestParam' | 'requestForm' | 'setRequestForm'>;
```
💊 이렇게 하는건 어떨까요? 그런데 interface를 꼭 써야하면 이렇게 하면 안될거 같아요!

2024-05-03 03:17 UTC, predict-woo commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
> +}
```suggestion
type PrintingBusinessFormThirdProps = Pick<PrintingBusinessFormProps, 'requestForm' | 'setRequestForm'> & {setFormError: React.Dispatch<React.SetStateAction<boolean>>};
```
💊 마찬가지 입니당

2024-05-03 07:21 UTC, babycroc requested changes
헿 나는 쉽게 approve를 주지 않겠다 
(@predict-woo 랑 @wjeongchoi 가 리뷰 엄청 잘해줘서 뿌듯)

- 피그마 디자인과 다른 부분들 중 나름 ux 측면에서 critical하다고 판단한 부분들
- 오작동하는 부분 중 의도된 바(추후 투두)가 아닌 부분
을 일단 먼저 고쳐주시구 완료되면 review rerequest + slack mention 부탁드려요

추가로
- PR 설명이 업데이트가 안 되어 있는 것 같아서 업데이트 해주시고 (고친 사항과 추후 TODO가 섞여 있어 무엇이 해결된거고 아닌건지 판단하기 어려움)
- 어 머라 말할라했더라 아 맞다 달력 반응형 적용 된건가요? 뭔가 관련 코드는 본 것 같은데 작동은 안 되는 것 같아서 확인차 여쭤봅니당~~

수고해따 오늘 출근은 잘 했나 ㅇ.ㅇ 다음에도 같이 동방 밤샘 합시다~~

2024-05-03 07:21 UTC, babycroc commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
> +  );
뭔가뭔가 변수명 규칙이 통일이 안 되어 있는 것 같은 느낌인데 
`a3printCount` -> `a3PrintCount`
`a3PrintCount` -> `a4PrintCount`
일단 p가 대문자인 게 맞을 것 같아요

2024-05-03 07:21 UTC, babycroc commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
> +    setRequestForm({ ...requestForm, krPhoneNumber: phoneNumber });
ts error 있는 것 같은데 확인해주세용
<img width="628" alt="image" src="https://github.com/academic-relations/ar-002-clubs/assets/33417582/d421fc9c-439e-45ce-b17a-acd4c7c86a6b">

2024-05-03 07:21 UTC, babycroc commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
> +        />
요거 "흰 테두리 재단" 선택이 불가능해요 
(`setIsFirstOptionSelected={setRequireMarginChopping}` 때문)

2024-05-06 11:47 UTC, Engineer-JJHaMa commented on packages/web/src/constants/printingBusiness.ts
> +(동아리별로 반기당 A3용지 최대 50매, A4 용지 최대 50매 인쇄 가능)`;
함수로 변경하여 이후에 인터페이스 구현되면 연결하기 용이하도록 할게요!

2024-05-06 11:51 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
> +  );
👍👍

2024-05-06 11:59 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
> +        />
헉...졸면서 짯나

2024-05-06 12:07 UTC, Engineer-JJHaMa commented on packages/web/src/constants/printingBusiness.ts
> +(동아리별로 반기당 A3용지 최대 50매, A4 용지 최대 50매 인쇄 가능)`;
동아리명 + 남은 출력매수 받는 함수로 변경 완료했습니다!

2024-05-06 12:07 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/TimeSlotList.tsx
> +  /* Inside auto layout */
메모..

2024-05-06 12:17 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
> +    setRequestForm({ ...requestForm, krPhoneNumber: phoneNumber });
인터페이스에서 krPhonNumber 타입을 010-....-.... 형식만 받도록 설정해 두었는데,
숫자 하나씩 전화번호를 입력해야 하는 상황을 고려하면 인터페이스가 바뀌는게 맞을것 같습니다.
인터페이스 수정하도록 할게요!

2024-05-06 12:26 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/SingleDateSelectionCalendar.tsx
> +      const parsePx = (val: string) => parseInt(val.replace("px", ""));
🫢🫢

2024-05-06 12:52 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/SingleDateSelectionCalendar.tsx
> +      const parsePx = (val: string) => parseInt(val.replace("px", ""));
오오... 감사합니다!

2024-05-06 12:52 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/SingleDateSelectionCalendar.tsx
> +    />
확인!

2024-05-06 12:56 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
> +}
좋습니다. 주요한 차이는 오버로딩이 가능한가 인것 같은데 그런 컴포넌트의 Props를 수정하여 사용할 일은 없으니 괜찮을 것 같아요!

2024-05-06 13:06 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
> +      />
인터페이스 수정까지 승인되어서 한번에 해버림!

2024-05-08 03:40 UTC, babycroc commented
내 리뷰 이후에 커밋이 없는데 뭘 확인하면 되는걸까용 @Engineer-JJHaMa

2024-05-08 03:48 UTC, Engineer-JJHaMa commented
@babycroc 헉 푸시 안되었었구나... 푸시했어요!

2024-05-08 04:06 UTC, babycroc approved these changes
요구한 걸 잘 고쳐줬어요!!! 코멘트 하나 단거만 바로 반영해서 머지하면 될 것 같구
사실 아직 안된 부분이 좀 있는데 가능하면 같이 반영해서 머지해주고 어려우면 이슈로 만들어서 남겨주세용
- 인쇄 목적 입력 안했을 때 에러메세지 띄우기
![image](https://github.com/academic-relations/ar-002-clubs/assets/33417582/14c92917-90a5-494a-8ed5-35895ec82ac9)
- 맨 처음에 FormThird 들어가면 선택된 시간이 없는데 (초기 디폴트 값으로) 가능한 가장 빠른 수령 시간이 선택되게 해주세요
![image](https://github.com/academic-relations/ar-002-clubs/assets/33417582/72feac17-df99-45a1-a947-10da11e454af)

2024-05-08 04:06 UTC, babycroc commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/TimeSlotList.tsx
> +  width: ${({ calendarSize }) => (calendarSize === "md" ? "450px" : "300px")};
저번에 말한 "md" 또는 "sm"일 때는 width 100%로 하는 것
```suggestion
  width: ${({ calendarSize }) => (calendarSize === "lg" ? "300px" : "100%")};
```

2024-05-09 13:22 UTC, Engineer-JJHaMa commented on packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/TimeSlotList.tsx
> +  width: ${({ calendarSize }) => (calendarSize === "md" ? "450px" : "300px")};
수정했습니다!

2024-05-10 13:15 UTC, Engineer-JJHaMa commented
최종 반영된 내용 정리입니다
- 시각선택 버튼 반응형 적용 완료되었고, 디폴트로 가장 빨리 받을 수 있는 시간(당일 21:00)으로 설정했습니다.
- 인쇄 목적을 비워둘 경우 에러메세지가 발생하며, 신청 버튼이 비활성화 됩니다.

2024-05-10 13:15 UTC, merged